#!/bin/bash
# check ClamAV and Snort while surfing over wifi
	while trap 'exit 0' SIGINT ;
do
		if [[ $EUID != 0 ]] ;
	then
		sudo $0
	else
		clear ;
		ps aux | grep -v grep | grep clamd && ps aux | grep -v grep | grep snort ;
		echo -e "\n :: \n" ;
		/usr/games/fortune ;
		echo -e "\n :: \n" ;
		snortup ;
		sleep 9 ;		
	fi
done
