#!/bin/bash
# mindevenviro hi
# startup file on /usr/local/bin
LANG="C" ;
to_star_up(){
xsetroot -solid yellow &
sleep 0.6 ;
oclock -hour red -minute white -bd white -bg black -jewel green -shape -geometry 70x75-6+3 &
xload -g 60x58-10+91 -fg "grey" -bg "black" -bw 1 &
setsid xscreensaver -display :0 -no-splash >/dev/null 2>&1 < /dev/null &
xcompmgr -c &
sleep 1 ;
terminator &
sleep 2 ;
feh-bg &
	}
		if [[ $(ps axu | grep -v grep | grep terminator) = '' ]] && \
		[[ $(ps axu | grep -v grep | grep xload) != '' ]] && \
		[[ $(ps axu | grep -v grep | grep xscreensaver) != '' ]] ;
	then
		terminator &

		elif [[ $(ps axu | grep -v grep | grep oclock) = '' ]] || \
		[[ $(ps axu | grep -v grep | grep xload) = '' ]] || \
		[[ $(ps axu | grep -v grep | grep xscreensaver) = '' ]] ;
	then
		to_star_up ;
	else
		exit 0 ;
fi
