#!/bin/bash
# startup file on /usr/local/bin

                if [[ $(ps axu | grep -v grep | grep -v hi_brutalchess | grep brutalchess) = '' ]] ;
        then
                brutalchess & hi ;
        else
                exit 0 ;
fi

