#!/bin/bash
# startup file on /usr/local/bin
LANG="C" ;
                if [[ $(ps axu | grep -v grep | grep -v hi_cheese | grep cheese) = '' ]] ;
        then
                cheese & hi ;
        else
                exit 0 ;
fi

