#!/bin/bash
# startup file on /usr/local/bin
LANG="C" ;
                if [[ $(ps axu | grep -v grep | grep -v hi_firefox-esr | grep firefox-esr) = '' ]] ;
        then
                firefox-esr & hi ;
        else
                exit 0 ;
fi

