#!/bin/bash
# startup file on /usr/local/bin

                if [[ $(ps axu | grep -v grep | grep -v hi_geany | grep geany) = '' ]] ;
        then
                geany & hi ;
        else
                exit 0 ;
fi

