#!/bin/bash
# startup file on /usr/local/bin

                if [[ $(ps axu | grep -v grep | grep -v hi_libreoffice | grep libreoffice) = '' ]] ;
        then
                libreoffice & hi ;
        else
                exit 0 ;
fi

