#!/bin/bash
# startup file on /usr/local/bin

                if [[ $(ps axu | grep -v grep | grep -v hi_playonlinux | grep playonlinux) = '' ]] ;
        then
                playonlinux & hi ;
        else
                exit 0 ;
fi

