#!/bin/bash
# startup file on /usr/local/bin
LANG="C" ;
                if [[ $(ps axu | grep -v grep | grep -v hi_transmission-gtk | grep transmission-gtk) = '' ]] ;
        then
                transmission-gtk & hi ;
        else
                exit 0 ;
fi

