#!/bin/bash
# startup file on /usr/local/bin

                if [[ $(ps axu | grep -v grep | grep -v hi_wicd-client | grep wicd-client) = '' ]] ;
        then
                wicd-client -n & hi ;
        else
                exit 0 ;
fi

