#!/bin/bash

# installs min-dev-enviro

###     WARNING:    DON'T EDIT ANYTHING BELOW       ###

LANG="C" ;
myPrograms="wicd scrot playonlinux mupdf terminator xul-ext-ublock-origin firefox-esr vlc feh xclip geany transmission xscreensaver vtwm oss-compat alsa-utils x11-apps xdm xorg zip rar openssl clamav-freshclam clamav-milter clamdscan clamav-daemon clamav-base clamav mysql-client mysql-server php7.0 dwww apache2 git sendmail python-gtk2-dbg shellcheck libcgi-pm-perl perl fortunes figlet mc mutt eject nano nmon " ;
environinstall="serv-if-up sCRYPtUPdater shi3lD stop_shield start_shield feh-bg hi hi_geany hi_transmission-gtk hi_firefox-esr hi_playonlinux hi_vlc hi_wicd-client search mysql_cp_db snortup check " ;

		if [ ! $EUID = 0 ] ;
	then
		echo -e "please sudo" ;
		exit 0 ;
else
		if [[ ! $(cat /proc/net/route | head -n2 | awk '{print $1}' | tail -n1) =~ 'eno|eth' ]] ;
	then
		interface="$(cat /proc/net/route | head -n2 | awk '{print $1}' | tail -n1)";
fi
		if [[ $PWD =~ 'min-dev-enviro' ]] && [[ $(ps axu | grep -v grep | grep install) != '' ]] ;
	then

	nNuM1=$(echo "$environinstall" | wc -w) ;
	nNuM2=$(echo "$myPrograms" | wc -w) ;

		if [[ "$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" != '' ]] ;
	then
		tmpfolder="$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" ;
	else
		tmpfolder="/tmp" ;
fi	
		spin='.oOo' ; i=0 ;
		spin2='-\|/' ;
		
		while [[ "$nNuM1" != "0" ]] ;
	do
		clear ;
		toCopyPath=$(awk '{print $'"$nNuM1"'}'<<<"$environinstall") ;		
		sudo cp -f "$PWD/$toCopyPath" "/usr/local/bin/$toCopyPath" ;
		sudo chown root:root "/usr/local/bin/$toCopyPath" ;
		sudo chmod 4755 "/usr/local/bin/$toCopyPath" ;
		sudo chmod u+s "/usr/local/bin/$toCopyPath" &&
		echo -e "\n ... BEGINing INSTALLATION ::\n" ;		
		i=$(( (i+1) %4 )) ; printf "\r ${spin2:$i:1} $toCopyPath in path: $nnumberr${spin:$i:1} " | tee -a "/home/$SUDO_USER/.installed" ; sleep .1 ;
		((nNuM1--)) ;
done

	echo -e " ... clearing files" ;

	# by an update clear from double entries
	sed '/alias /d' /home/$SUDO_USER/.bashrc > $tmpfolder/.bashrc ;
	cp -f $tmpfolder/.bashrc /home/$SUDO_USER/.bashrc ;
	sed '/noclobber /d' /home/$SUDO_USER/.bashrc > $tmpfolder/.bashrc ;
	cp -f $tmpfolder/.bashrc /home/$SUDO_USER/.bashrc ;

	# by an update clear from double entries
	sed '/Alias /d' /etc/apache2/sites-available/000-default.conf > $tmpfolder/000-default.conf ;
	cp -f $tmpfolder/000-default.conf /etc/apache2/sites-available/000-default.conf ;
	
	# by an update clear from double entries	
	sed -e '/Downloads auto bind/d' /etc/fstab >| $tmpfolder/fstab ;
	cp -f $tmpfolder/fstab /etc/fstab ;

	echo -e "\n ... save vendors MAC-Address" ;
	ip link show | grep ether | awk '{print $2}' | tee -a "/home/$SUDO_USER/.vendorsmac" ;
	chown "$SUDO_USER":"$SUDO_USER" "/home/$SUDO_USER/.vendorsmac" ;

	echo -e "\n ... create /home/$SUDO_USER Directories" ;
	mkdir -p /home/$SUDO_USER/{testphp,testbash,testperl,testpython,Downloads,Pictures,Documents,Music,Ableton} 2>/dev/null ;
	chown -R $SUDO_USER:$SUDO_USER /home/$SUDO_USER ;

	echo -e "\n ... set background Pictures" ;
	unzip wallpapers.zip -df /home/$SUDO_USER/Pictures/ && wait ;
	chown -R "$SUDO_USER":"$SUDO_USER" /home/$SUDO_USER/Pictures/* ;

	echo -e "\n ... copy the startup sound to /home/$SUDO_USER/Music/" ;
	cp -f 76256__ganscaile__startup.mp3 /home/$SUDO_USER/Music/ && wait ;
	chown "$SUDO_USER":"$SUDO_USER" /home/$SUDO_USER/Music/* ;

	echo -e "\n ... I'm going to install programs\n ... copy sources.list" ;
	cp -f sources.list /etc/apt/sources.list
	echo -e "\n ... I do an update" ;	
	apt-get update && wait ;

		while [[ "$nNuM2" != "0" ]] ;
	do
		toInst=$(awk '{print $'"$nNuM2"'}'<<<"$myPrograms") ;

		wH3RE=$(whereis "$toInst" | cut -f2 -d: | cut -f2 -d\ ) ;

		if [[ "${#wH3RE}" != "0" ]] ;
	then
		apPR="$toInst, allready installed" | tee -a "/home/$SUDO_USER/.installed" ;
		echo -e "\n$apPR" ;
		((nNuM2--)) ;
	else
		echo -e "\ninstalling ${toInst}..." ;
		apt-get -f -m -y install "$toInst" | tee -a "/home/$SUDO_USER/.installed" && wait ;
		wait ;
		sleep 1 ;
		apPR="$toInst, INSTALLED!" ;
		echo -e "\n$apPR" | tee -a "/home/$SUDO_USER/.installed" ;
		sleep 0.5 ;
		((nNuM2--)) ;
fi
		if [ "$nNuM2" = "0" ]
	then
		echo -e "\n ... apt-get done." ;
		sleep 0.5 ;
fi
		printf "\r ... testing for apps, $nNuM2 remaining, $apPRn" ; sleep 0.5 ;
done

	echo -e "\n ... copy Xresources" ;
	cp -f Xresources /etc/X11/xdm/ ;
	chmod 755 /etc/X11/xdm/Xresources ;

	echo -e "\n ... update .bashrc" ;
	echo "set -o noclobber" >> /home/$SUDO_USER/.bashrc ;	
	echo "alias ls='ls --color=auto -s'" >> /home/$SUDO_USER/.bashrc ;
	echo "alias down='sudo init 0'" >> /home/$SUDO_USER/.bashrc ;
	echo "alias reboot='sudo init 6'" >> /home/$SUDO_USER/.bashrc ;

	echo -e "\n ... copy the ini file to /home/$SUDO_USER/.config/mc/" ;
	mkdir -p /home/$SUDO_USER/.config/mc 2>/dev/null ;
	cp -f ini /home/$SUDO_USER/.config/mc/ini ;
	chown "$SUDO_USER":"$SUDO_USER" /home/$SUDO_USER/.config ;

	echo -e "\n ... copy the config file to /home/$SUDO_USER/.config/terminator/config" ;
	mkdir -p /home/$SUDO_USER/.config/terminator 2>/dev/null ;
	cp -f config /home/$SUDO_USER/.config/terminator/config ;
	chown "$SUDO_USER":"$SUDO_USER" /home/$SUDO_USER/.config ;
	
	echo -e "\n ... copy the .twmrc file to /home/$SUDO_USER" ;
	cp -f twmrc /home/$SUDO_USER/.twmrc ;
	chown "$SUDO_USER":"$SUDO_USER" /home/$SUDO_USER/.twmrc ;
	
	echo -e "\n ... copy the playlist to /home/$SUDO_USER" ;
	cp -f playlist.m3u /home/$SUDO_USER/playlist.m3u ;
	chown "$SUDO_USER":"$SUDO_USER" /home/$SUDO_USER/playlist.m3u ;
	
	echo -e "\n ... copy the .xscreensaver file to /home/$SUDO_USER" ;
	cp -f xscreensaver /home/$SUDO_USER/.xscreensaver ;
	chown "$SUDO_USER":"$SUDO_USER" /home/$SUDO_USER/.xscreensaver ;

	echo -e "\n ... copy VLC skin" ;
	cp -f STRYPER-VLC.vlt /usr/share/vlc/skins2/ ;
	chmod 755 /usr/share/vlc/skins2/STRYPER-VLC.vlt ;
	cp -f 169311-inkyV2.vlt /usr/share/vlc/skins2/ ;
	chmod 755 /usr/share/vlc/skins2/169311-inkyV2.vlt ;
	cp -f default.vlt /usr/share/vlc/skins2/ ;
	chmod 755 /usr/share/vlc/skins2/default.vlt ;
	cp -f Slick\ Iphone\ Skin.vlt /usr/share/vlc/skins2/ ;
	chmod 755 /usr/share/vlc/skins2/Slick\ Iphone\ Skin.vlt ;
	
	echo -e "\n ... set the upload path for PHP scripts" ;
	rm -f /var/www/html/index*
	mkdir -p /var/www/html/testphp/ 2>/dev/null ;
	cp -f README.html /var/www/html/README.html ;
	chown www-data:www-data /var/www/html/README.html ;
	
	echo "Alias /testphp/ /var/www/html/testphp/" >> /etc/apache2/sites-available/000-default.conf ;
	
	echo -e "\n ... check for cgi-bin on drive" ;
	
		if [[ ! "$(cat /etc/apache2/sites-available/000-default.conf | grep cgi-bin)" =~ '/usr/lib/cgi-bin/' ]] ;
	then
		mkdir -p /usr/lib/cgi-bin/ 2>/dev/null ;
		echo -e "\nScriptAlias /cgi-bin/ /usr/lib/cgi-bin/\r
		<Directory "/usr/lib/cgi-bin">\r
		AllowOverride None\r
		Options +ExecCGI +MultiViews +SymLinksIfOwnerMatch\r
		Order allow,deny\r
		Allow from all\r
		</Directory>\n" >> /etc/apache2/sites-available/000-default.conf ;
	else
		echo -e "\n ... cgi-bin dir exists" ;
fi
		echo -e "\n ... update apache2 configuration" ;
		a2enmod cgid && wait ;
		
		echo -e "\n ... restart server" ;
		systemctl restart apache2.service && wait ;

		echo -e "\n ... put $SUDO_USER/Downloads in a Jail" ;
		echo "/dev/shm /home/$SUDO_USER/Downloads auto bind 0 0" | tee -a /etc/fstab ;

		echo -e "\n ... set the rights for installed (to remove it later)" ;
		chown "$SUDO_USER":"$SUDO_USER" "/home/$SUDO_USER/.installed" ;

		echo -e "\n ... set the rights for .wH0rUNSon " ;
		touch $HOME/.wH0rUNSon && chown $SUDO_USER:$SUDO_USER $HOME/.wH0rUNSon ;
		
		# workaround for debconf's snort
		apt-get -f -m -y install snort && wait ;
		# reconfigure all
		dpkg --configure -a && wait ;
		# clean and autoremove
		apt-get clean ;
		apt -f -y -m autoremove ;
		
		echo -e "\n\n ... Congratulations we have min-dev-enviro successfully installed!\r" ;
else
		echo -e "\n run this script from min-dev-enviro folder\r" ;
fi
fi
