#!/bin/bash
# installs min-dev-enviro
###     WARNING:    DON'T EDIT ANYTHING BELOW       ###

LANG="C" ;
myPrograms="wicd brutalchess libreoffice-writer tidy cheese gimp scrot mupdf terminator playonlinux wine64 wine64-tools wine64-preloader xul-ext-ublock-origin firefox-esr vlc feh xclip geany transmission openvpn xscreensaver vtwm oss-compat alsa-utils xcompmgr x11-apps xdm xorg zip rar openssl clamav-freshclam clamav-milter clamdscan clamav-daemon clamav-base clamav mysql-client mysql-server php7.0 php7.0-cli php7.0-mcrypt php7.0-intl php7.0-mysql php7.0-curl php7.0-gd php7.0-soap php7.0-xml php7.0-zip php7.0-readline php7.0-opcache php7.0-json php7.0-gd dwww apache2 git sendmail python-gtk2-dbg shellcheck libcgi-pm-perl perl fortunes figlet mc mutt eject nano nmon " ;
environinstall="server-monitor redundanz serv-if-up sCRYPtUPdater shi3lD stop_shield start_shield feh-bg hi hi_cheese hi_brutalchess hi_libreoffice hi_geany hi_gimp hi_transmission-gtk hi_firefox-esr hi_playonlinux hi_vlc hi_wicd-client search mysql_cp_db set_mysql_passwd openpdf takeshot install " ;
apPRn='' ;
		if [ ! $EUID = 0 ] ;
	then
		echo -e "please sudo" ;
		exit 0 ;
else
		if [[ ! $(cat /proc/net/route | head -n2 | awk '{print $1}' | tail -n1) =~ 'eno|eth' ]] ;
	then
		interface="$(cat /proc/net/route | head -n2 | awk '{print $1}' | tail -n1)";
fi
		if [ ! -e /home/$SUDO_USER/.installed ] && [[ $PWD =~ 'M1ND3V3NV1R0' ]] ;
	then

	nNuM1=$(echo "$environinstall" | wc -w) ;
	nNuM2=$(echo "$myPrograms" | wc -w) ;

		if [[ "$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" != '' ]] ;
	then
		tmpfolder="$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" ;
	else
		tmpfolder="/tmp" ;
fi	
		spin='.oOo' ; i=0 ;
		spin2='-\|/' ;
		
		while [[ "$nNuM1" != "0" ]] ;
	do
		clear ;
		toCopyPath=$(awk '{print $'"$nNuM1"'}'<<<"$environinstall") ;
		sudo cp -f "$PWD/$toCopyPath" "/usr/local/bin/$toCopyPath" ;
		sudo chown root:root "/usr/local/bin/$toCopyPath" ;
		sudo chmod 4755 "/usr/local/bin/$toCopyPath" ;
		sudo chmod u+s "/usr/local/bin/$toCopyPath" &&
		echo -e "\n ... copying files ::\n" ;
		i=$(( (i+1) %4 )) ; printf "\r ... ${spin:$i:1}.${spin2:$i:1} $toCopyPath ." | tee -a "/home/$SUDO_USER/.installed" ; sleep .1 ;
		((nNuM1--)) ;
done

	echo -e "\r\n ... clearing files" ;
	
	# by an update clear from double entries in 000-default.conf
	sed '/Alias /d' /etc/apache2/sites-available/000-default.conf > $tmpfolder/000-default.conf 2>/dev/null ;
	cp -f $tmpfolder/000-default.conf /etc/apache2/sites-available/000-default.conf 2>/dev/null ;
	
	# by an update clear from double entries in fstab
	sed -e '/Downloads auto bind/d' /etc/fstab >| $tmpfolder/fstab 2>/dev/null ;
	cp -f $tmpfolder/fstab /etc/fstab 2>/dev/null ;
	
	# by an update clear from double entries in clamd.conf
	sed -e '/ScanOnAccess /d' /etc/clamav/clamd.conf  >| $tmpfolder/clamd.conf 2>/dev/null ;
	cp -f $tmpfolder/clamd.conf /etc/clamav/clamd.conf 2>/dev/null ;
	
	# by an update clear from double entries in clamd.conf
	sed -e '/OnAccessMountPath /d' /etc/clamav/clamd.conf  >| $tmpfolder/clamd.conf 2>/dev/null ;
	cp -f $tmpfolder/clamd.conf /etc/clamav/clamd.conf 2>/dev/null ;	

	echo -e "\n ... save vendors MAC-Address" ;
	ip link show | grep ether | awk '{print $2}' | tee "/home/$SUDO_USER/.vendorsmac" ;
	chown $SUDO_USER:$SUDO_USER "/home/$SUDO_USER/.vendorsmac" ;

	echo -e "\n ... create /home/$SUDO_USER Directories" ;
	mkdir -p /home/$SUDO_USER/{testphp,testbash,testperl,testpython,Downloads,Pictures,Documents,Music,Ableton} ;
	chown -R $SUDO_USER:$SUDO_USER /home/$SUDO_USER ;

	echo -e "\n ... copy the startup sound to /home/$SUDO_USER/Music/" ;
	cp -f 76256__ganscaile__startup.mp3 /home/$SUDO_USER/Music/ && wait ;
	chown $SUDO_USER:$SUDO_USER /home/$SUDO_USER/Music/* ;

	echo -e "\n ... I'm going to install programs\n ... copy sources.list" ;
	cp -f sources.list /etc/apt/sources.list ;
	wget -q "http://deb.playonlinux.com/public.gpg" -O- | sudo apt-key add - ;
	wget "http://deb.playonlinux.com/playonlinux_jessie.list" -O /etc/apt/sources.list.d/playonlinux.list ;
	echo -e "\n ... I do an update" ;	
	apt-get update && wait ;

	printf "your email-address on github.com: "; read eM4il
	
		if	[[ "$eM4il" != '' ]] ;
	then
		sudo -u $SUDO_USER ssh-keygen -t rsa -b 4096 -C "$eM4il"
		eX1tC0de=$(echo $?) ;
		wait ;
		
		if [[ "$eX1tC0de" != 0 ]] ;
	then
		echo -e "\n REMEMBER ssh-keygen -t rsa -b 4096 -C your-email@server.tld \nto add a github.com account" | tee -a /home/$SUDO_USER/.installed ;
	else
		echo "eval $(ssh-agent -s)" >> /home/$SUDO_USER/.bashrc ;
		echo "ssh-add ~/.ssh/id_rsa" >> /home/$SUDO_USER/.bashrc ;
		sudo -u $SUDO_USER ssh-keygen -p ;
	fi
	else
		echo " no github.com email."
	fi
		
		while [[ "$nNuM2" != "0" ]] ;
	do
		toInst=$(awk '{print $'"$nNuM2"'}'<<<"$myPrograms") ;

		wH3RE=$(whereis "$toInst" | cut -f2 -d: | cut -f2 -d\ ) ;

		if [[ "${#wH3RE}" != "0" ]] ;
	then
		apPR="$toInst, allready installed" ;
		echo -e "\n$apPR" ;
		((nNuM2--)) ;
	else
		echo -e "\ninstalling ${toInst}..." ;
		apt-get -f -m -y --allow-change-held-packages install "$toInst" | tee -a "/home/$SUDO_USER/.installed" && wait ;
		wait ;
		sleep 1 ;
		apPR="$toInst, INSTALLED!" ;
		echo -e "\n$apPR" | tee -a "/home/$SUDO_USER/.installed" ;
		sleep 0.5 ;
		((nNuM2--)) ;
fi
		if [ "$nNuM2" = "0" ]
	then
		echo -e "\n ... apt-get done." ;
		sleep 0.5 ;
fi
		printf "\r ... testing for apps, $nNuM2 remaining, $apPRn" ; sleep 0.5 ;
done

	echo -e "\n ... set background Pictures" ;
	rm -R /home/$SUDO_USER/Pictures/* 2>/dev/null ;
	unzip wallpapers.zip -d /home/$SUDO_USER/Pictures && wait ;
	chown -R $SUDO_USER:$SUDO_USER /home/$SUDO_USER/Pictures/* ;

	echo -e "\n ... installing flash player for linux" ;
	tar -xf flash_player_npapi_linux.x86_64.tar.gz ;
	sudo cp -f libflashplayer.so /usr/lib/mozilla/plugins/ ;
	sudo cp -rf usr/* /usr/ ;
	sleep 0.5 ;
	rm -dRf LGPL/ usr/ libflashplayer.so license.pdf readme.txt ;

	echo -e "\n ... copy .bashrc" ;
	cp -f bashrc /home/$SUDO_USER/.bashrc ;
	chmod 644 /home/$SUDO_USER/.bashrc ;

	echo -e "\n ... copy mindevenviro.xpm" ;
	cp -f mindevenviro.xpm /usr/share/X11/xdm/pixmaps/mindevenviro.xpm ;
	chmod 644 /usr/share/X11/xdm/pixmaps/mindevenviro.xpm ;

	echo -e "\n ... copy Xresources" ;
	cp -f Xresources /etc/X11/xdm/ ;
	chmod 755 /etc/X11/xdm/Xresources ;

	echo -e "\n ... copy the ini file to /home/$SUDO_USER/.config/mc/" ;
	mkdir -p /home/$SUDO_USER/.config/mc 2>/dev/null ;
	cp -f ini /home/$SUDO_USER/.config/mc/ini ;
	chown $SUDO_USER:$SUDO_USER /home/$SUDO_USER/.config ;

	echo -e "\n ... copy the config file to /home/$SUDO_USER/.config/terminator/config" ;
	mkdir -p /home/$SUDO_USER/.config/terminator 2>/dev/null ;
	cp -f config /home/$SUDO_USER/.config/terminator/config ;
	chown $SUDO_USER:$SUDO_USER /home/$SUDO_USER/.config ;
	
	echo -e "\n ... copy the .twmrc file to /home/$SUDO_USER" ;
	cp -f twmrc /home/$SUDO_USER/.twmrc ;
	chown $SUDO_USER:$SUDO_USER /home/$SUDO_USER/.twmrc ;
	
	echo -e "\n ... copy the playlist to /home/$SUDO_USER" ;
	cp -f playlist.m3u /home/$SUDO_USER/playlist.m3u ;
	chown $SUDO_USER:$SUDO_USER /home/$SUDO_USER/playlist.m3u ;
	
	echo -e "\n ... copy the .xscreensaver file to /home/$SUDO_USER" ;
	cp -f xscreensaver /home/$SUDO_USER/.xscreensaver ;
	chown $SUDO_USER:$SUDO_USER /home/$SUDO_USER/.xscreensaver ;

	echo -e "\n ... copy VLC skin" ;
	cp -f MyVLCtheme.vlt /usr/share/vlc/skins2/ ;
	chmod 755 /usr/share/vlc/skins2/MyVLCtheme.vlt  ;	
	
	echo -e "\n ... set the upload path for PHP scripts" ;
	rm -f /var/www/html/index*
	mkdir -p /var/www/html/testphp/ 2>/dev/null ;
	cp -f mindevenviro.png /var/www/html/ ;
	cp -f bottom.png /var/www/html/ ;
	chown www-data:www-data /var/www/html/mindevenviro.png ;
	cp -f README.html /var/www/html/ ;
	chown www-data:www-data /var/www/html/README.html ;
	
	echo "Alias /testphp/ /var/www/html/testphp/" >> /etc/apache2/sites-available/000-default.conf ;
	
	echo -e "ScanOnAccess True\nOnAccessMountPath /home/$SUDO_USER/Downloads" >> /etc/clamav/clamd.conf ;
	
	echo -e "\n ... check for cgi-bin on drive" ;
	
		if [[ ! "$(cat /etc/apache2/sites-available/000-default.conf | grep cgi-bin)" =~ '/usr/lib/cgi-bin/' ]] ;
	then
		mkdir -p /usr/lib/cgi-bin/ 2>/dev/null ;
		echo -e "\nScriptAlias /cgi-bin/ /usr/lib/cgi-bin/\r
		<Directory "/usr/lib/cgi-bin">\r
		AllowOverride None\r
		Options +ExecCGI +MultiViews +SymLinksIfOwnerMatch\r
		Order allow,deny\r
		Allow from all\r
		</Directory>\n" >> /etc/apache2/sites-available/000-default.conf ;
	else
		echo -e "\n ... cgi-bin dir exists" ;
fi
		echo -e "\n ... update apache2 configuration" ;
		a2enmod cgid && wait ;
		
		echo -e "\n ... restarting apache2 server" ;
		systemctl restart apache2.service && wait ;

		echo -e "\n ... put $SUDO_USER/Downloads in a Jail" ;
		echo "/dev/shm /home/$SUDO_USER/Downloads auto bind 0 0" | tee -a /etc/fstab ;

		echo -e "\n ... set the rights for installed (to remove it later)" ;		
		chown $SUDO_USER:$SUDO_USER "/home/$SUDO_USER/.installed" ;
		chmod 0660 "/home/$SUDO_USER/.installed"

		echo -e "\n ... set the rights for .wH0rUNSon " ;
		
		if [ -e /home/$SUDO_USER/.wH0rUNSon ] ;
	then
		echo " . .wH0rUNSon allready installed" | tee -a "/home/$SUDO_USER/.installed"
	else
		touch "/home/$SUDO_USER/.wH0rUNSon" && chown $SUDO_USER:$SUDO_USER "/home/$SUDO_USER/.wH0rUNSon" && chmod 0660 "/home/$SUDO_USER/.wH0rUNSon" ;
	fi
		# workaround for debconf's snort
		echo -e "\n ... installing snort " ;
		apt-get -f -m -y --allow-change-held-packages install snort && wait ;
		# reconfigure all
		echo -e "\n ... reconfiguring installed packages " ;
		dpkg --configure -a && wait ;
		# add i386 arch in 64bit system, to install wine32
		echo -e "\n ... add i386 arch in 64bit system, to install wine32" ;
		sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get -f -y -m --allow-change-held-packages install wine32 && wait ;
		# update upgrade clean and autoremove
		echo -e "\n ... update upgrade clean and autoremove" ;
		apt-get update && apt-get -f -y -m --allow-change-held-packages upgrade && wait ;
		apt-get clean &&
		apt -f -y -m autoremove &&
		
		# update mysql root password
		sudo mknod /run/mysqld/mysqld.sock p ;
		mysqlconn="mysql -u root" ;
		printf "enter your NEW mysql root password: "; read mysqlnewpass ;
		
		if	[[ "$mysqlnewpass" != '' ]] ;
	then
		if grep socket /etc/mysql/my.cnf && exitcode=$(echo $?) ;
	then
		if [[ $exitcode = 1 ]] ;
	then
		echo "socket = ">>/etc/mysql/my.cnf ;
		sed -i 's/\(socket *= *\).*/\1/run/mysqld/mysqld.sock/g' /etc/mysql/my.cnf ;
	fi
fi
		/etc/init.d/mysql stop && wait ;
		ps aux | grep -v grep | grep mysql | head -n1 | awk '{print $2}' | xargs kill -9 2>/dev/null;
		ps aux | grep -v grep | grep mysqld_safe | head -n1 | awk '{print $2}' | xargs kill -9 2>/dev/null;
		mysqld_safe --skip-grant-tables &
		$mysqlconn -e "use mysql; update mysql.user set password=password('$mysqlnewpass') where user='root';" && wait ;
		$mysqlconn -e "use mysql; update mysql.user set plugin='' where user='root';" && wait ;
		$mysqlconn -e "use mysql; FLUSH PRIVILEGES;" && wait ;
		ps aux | grep -v grep | grep mysqld_safe | head -n1 | awk '{print $2}' | xargs kill -9 2>/dev/null;
		echo -e "\n ... update mysql root passwords" ;
		sed -i "s/\(p4SSWORD *= *\).*/\1$mysqlnewpass/" /etc/mysql_cp_db_password.conf ;
		sed -i "s/\(plugin_password *= *\).*/\1/" /etc/mysql_cp_db_password.conf ;
	fi
	# update mysql root password END
	
		echo -e "\n\n ... Congratulations we have M1ND3V3NV1R0 successfully installed!\r"
		read -p " ... continue?" ;
		echo -e "\n ... RESTART IN 6 SECONDS...\r" ;
		sleep 6 ;
		init 6 ;
else
		echo -e "\n M1ND3V3NV1R0 allready installed!\n run this script from within the folder M1ND3V3NV1R0\n do: rm /home/$SUDO_USER/.installed\n after installation, system will restart." ;
		echo -e "\n you should be in the M1ND3V3NV1R0 folder."
fi
fi
