#!/bin/bash
# installs min-dev-enviro
###     WARNING:    DON'T EDIT ANYTHING BELOW       ###

LANG="C" ;
myPrograms="wicd brutalchess libreoffice-writer scrot mupdf terminator playonlinux wine64 wine64-tools wine64-preloader xul-ext-ublock-origin firefox-esr vlc feh xclip geany transmission xscreensaver vtwm oss-compat alsa-utils xcompmgr x11-apps xdm xorg zip rar openssl clamav-freshclam clamav-milter clamdscan clamav-daemon clamav-base clamav mysql-client mysql-server php7.0 dwww apache2 git sendmail python-gtk2-dbg shellcheck libcgi-pm-perl perl fortunes figlet mc mutt eject nano nmon " ;
environinstall="serv-if-up sCRYPtUPdater shi3lD stop_shield start_shield feh-bg hi hi_brutalchess hi_libreoffice hi_geany hi_transmission-gtk hi_firefox-esr hi_playonlinux hi_vlc hi_wicd-client search mysql_cp_db snortup check install " ;

		if [ ! $EUID = 0 ] ;
	then
		echo -e "please sudo" ;
		exit 0 ;
else
		if [[ ! $(cat /proc/net/route | head -n2 | awk '{print $1}' | tail -n1) =~ 'eno|eth' ]] ;
	then
		interface="$(cat /proc/net/route | head -n2 | awk '{print $1}' | tail -n1)";
fi
		if [ ! -e /home/$SUDO_USER/.installed ] && [[ $PWD =~ 'min-dev-enviro' ]] ;
	then

	nNuM1=$(echo "$environinstall" | wc -w) ;
	nNuM2=$(echo "$myPrograms" | wc -w) ;

		if [[ "$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" != '' ]] ;
	then
		tmpfolder="$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" ;
	else
		tmpfolder="/tmp" ;
fi	
		spin='.oOo' ; i=0 ;
		spin2='-\|/' ;
		
		while [[ "$nNuM1" != "0" ]] ;
	do
		clear ;
		toCopyPath=$(awk '{print $'"$nNuM1"'}'<<<"$environinstall") ;
		sudo cp -f "$PWD/$toCopyPath" "/usr/local/bin/$toCopyPath" ;
		sudo chown root:root "/usr/local/bin/$toCopyPath" ;
		sudo chmod 4755 "/usr/local/bin/$toCopyPath" ;
		sudo chmod u+s "/usr/local/bin/$toCopyPath" &&
		echo -e "\n ... copying files ::\n" ;
		i=$(( (i+1) %4 )) ; printf "\r ... ${spin:$i:1}.${spin2:$i:1} $toCopyPath ." | tee -a "/home/$SUDO_USER/.installed" ; sleep .1 ;
		((nNuM1--)) ;
done

	echo -e "\r\n ... clearing files" ;

	# by an update clear from double entries in .bashrc
	sed '/alias /d' /home/$SUDO_USER/.bashrc > $tmpfolder/.bashrc 2>/dev/null ;
	cp -f $tmpfolder/.bashrc /home/$SUDO_USER/.bashrc 2>/dev/null ;
	sed '/set -o noclobber/d' /home/$SUDO_USER/.bashrc > $tmpfolder/.bashrc 2>/dev/null ;
	cp -f $tmpfolder/.bashrc /home/$SUDO_USER/.bashrc 2>/dev/null ;
	sed '/cd && pwd/d' /home/$SUDO_USER/.bashrc > $tmpfolder/.bashrc 2>/dev/null ;
	cp -f $tmpfolder/.bashrc /home/$SUDO_USER/.bashrc 2>/dev/null ;	

	# by an update clear from double entries in 000-default.conf
	sed '/Alias /d' /etc/apache2/sites-available/000-default.conf > $tmpfolder/000-default.conf 2>/dev/null ;
	cp -f $tmpfolder/000-default.conf /etc/apache2/sites-available/000-default.conf 2>/dev/null ;
	
	# by an update clear from double entries in fstab
	sed -e '/Downloads auto bind/d' /etc/fstab >| $tmpfolder/fstab 2>/dev/null ;
	cp -f $tmpfolder/fstab /etc/fstab 2>/dev/null ;
	
	# by an update clear from double entries in clamd.conf
	sed -e '/ScanOnAccess /d' /etc/clamav/clamd.conf  >| $tmpfolder/clamd.conf 2>/dev/null ;
	cp -f $tmpfolder/clamd.conf /etc/clamav/clamd.conf 2>/dev/null ;
	
	# by an update clear from double entries in clamd.conf
	sed -e '/OnAccessMountPath /d' /etc/clamav/clamd.conf  >| $tmpfolder/clamd.conf 2>/dev/null ;
	cp -f $tmpfolder/clamd.conf /etc/clamav/clamd.conf 2>/dev/null ;	

	echo -e "\n ... save vendors MAC-Address" ;
	ip link show | grep ether | awk '{print $2}' | tee "/home/$SUDO_USER/.vendorsmac" ;
	chown $SUDO_USER:$SUDO_USER "/home/$SUDO_USER/.vendorsmac" ;

	echo -e "\n ... create /home/$SUDO_USER Directories" ;
	mkdir -p /home/$SUDO_USER/{testphp,testbash,testperl,testpython,Downloads,Pictures,Documents,Music,Ableton} ;
	chown -R $SUDO_USER:$SUDO_USER /home/$SUDO_USER ;

	echo -e "\n ... copy the startup sound to /home/$SUDO_USER/Music/" ;
	cp -f 76256__ganscaile__startup.mp3 /home/$SUDO_USER/Music/ && wait ;
	chown $SUDO_USER:$SUDO_USER /home/$SUDO_USER/Music/* ;

	echo -e "\n ... I'm going to install programs\n ... copy sources.list" ;
	cp -f sources.list /etc/apt/sources.list ;
	wget -q "http://deb.playonlinux.com/public.gpg" -O- | sudo apt-key add - ;
	wget "http://deb.playonlinux.com/playonlinux_jessie.list" -O /etc/apt/sources.list.d/playonlinux.list ;
	echo -e "\n ... I do an update" ;	
	apt-get update && wait ;

		while [[ "$nNuM2" != "0" ]] ;
	do
		toInst=$(awk '{print $'"$nNuM2"'}'<<<"$myPrograms") ;

		wH3RE=$(whereis "$toInst" | cut -f2 -d: | cut -f2 -d\ ) ;

		if [[ "${#wH3RE}" != "0" ]] ;
	then
		apPR="$toInst, allready installed" ;
		echo -e "\n$apPR" ;
		((nNuM2--)) ;
	else
		echo -e "\ninstalling ${toInst}..." ;
		apt-get -f -m -y --allow-change-held-packages install "$toInst" | tee -a "/home/$SUDO_USER/.installed" && wait ;
		wait ;
		sleep 1 ;
		apPR="$toInst, INSTALLED!" ;
		echo -e "\n$apPR" | tee -a "/home/$SUDO_USER/.installed" ;
		sleep 0.5 ;
		((nNuM2--)) ;
fi
		if [ "$nNuM2" = "0" ]
	then
		echo -e "\n ... apt-get done." ;
		sleep 0.5 ;
fi
		printf "\r ... testing for apps, $nNuM2 remaining, $apPRn" ; sleep 0.5 ;
done

	echo -e "\n ... set background Pictures" ;
	rm -R /home/$SUDO_USER/Pictures/* 2>/dev/null ;
	unzip wallpapers.zip -d /home/$SUDO_USER/Pictures && wait ;
	chown -R $SUDO_USER:$SUDO_USER /home/$SUDO_USER/Pictures/* ;

	echo -e "\n ... copy Xresources" ;
	cp -f Xresources /etc/X11/xdm/ ;
	chmod 755 /etc/X11/xdm/Xresources ;

	echo -e "\n ... update .bashrc" ;
	echo "set -o noclobber" >> /home/$SUDO_USER/.bashrc ;	
	echo "alias ls='ls --color=auto -sh'" >> /home/$SUDO_USER/.bashrc ;
	echo "alias down='sudo init 0'" >> /home/$SUDO_USER/.bashrc ;
	echo "alias vol='alsamixer'" >> /home/$SUDO_USER/.bashrc ;
	echo "alias works='tail -f .wH0rUNSon'" >> /home/$SUDO_USER/.bashrc ;
	echo "alias post='sudo -u root mutt'" >> /home/$SUDO_USER/.bashrc ; 
	echo "alias reboot='sudo init 6'" >> /home/$SUDO_USER/.bashrc ;	
	echo "alias | sed -n 's/alias //p ;'" >> /home/$SUDO_USER/.bashrc ;
	echo "cd && pwd" >> /home/$SUDO_USER/.bashrc ;

	echo -e "\n ... copy the ini file to /home/$SUDO_USER/.config/mc/" ;
	mkdir -p /home/$SUDO_USER/.config/mc 2>/dev/null ;
	cp -f ini /home/$SUDO_USER/.config/mc/ini ;
	chown $SUDO_USER:$SUDO_USER /home/$SUDO_USER/.config ;

	echo -e "\n ... copy the config file to /home/$SUDO_USER/.config/terminator/config" ;
	mkdir -p /home/$SUDO_USER/.config/terminator 2>/dev/null ;
	cp -f config /home/$SUDO_USER/.config/terminator/config ;
	chown $SUDO_USER:$SUDO_USER /home/$SUDO_USER/.config ;
	
	echo -e "\n ... copy the .twmrc file to /home/$SUDO_USER" ;
	cp -f twmrc /home/$SUDO_USER/.twmrc ;
	chown $SUDO_USER:$SUDO_USER /home/$SUDO_USER/.twmrc ;
	
	echo -e "\n ... copy the playlist to /home/$SUDO_USER" ;
	cp -f playlist.m3u /home/$SUDO_USER/playlist.m3u ;
	chown $SUDO_USER:$SUDO_USER /home/$SUDO_USER/playlist.m3u ;
	
	echo -e "\n ... copy the .xscreensaver file to /home/$SUDO_USER" ;
	cp -f xscreensaver /home/$SUDO_USER/.xscreensaver ;
	chown $SUDO_USER:$SUDO_USER /home/$SUDO_USER/.xscreensaver ;

	echo -e "\n ... copy VLC skin" ;
	cp -f STRYPER-VLC.vlt /usr/share/vlc/skins2/ ;
	chmod 755 /usr/share/vlc/skins2/STRYPER-VLC.vlt ;
	cp -f 169311-inkyV2.vlt /usr/share/vlc/skins2/ ;
	chmod 755 /usr/share/vlc/skins2/169311-inkyV2.vlt ;
	cp -f default.vlt /usr/share/vlc/skins2/ ;
	chmod 755 /usr/share/vlc/skins2/default.vlt ;
	cp -f Slick\ Iphone\ Skin.vlt /usr/share/vlc/skins2/ ;
	chmod 755 /usr/share/vlc/skins2/Slick\ Iphone\ Skin.vlt ;
	cp -f Alienware\ Darkstar.vlt /usr/share/vlc/skins2/ ;
	chmod 755 /usr/share/vlc/skins2/Alienware\ Darkstar.vlt  ;
	
	echo -e "\n ... set the upload path for PHP scripts" ;
	rm -f /var/www/html/index*
	mkdir -p /var/www/html/testphp/ 2>/dev/null ;
	cp -f README.html /var/www/html/README.html ;
	chown www-data:www-data /var/www/html/README.html ;
	
	echo "Alias /testphp/ /var/www/html/testphp/" >> /etc/apache2/sites-available/000-default.conf ;
	
	echo -e "ScanOnAccess True\nOnAccessMountPath /home/$SUDO_USER/Downloads" >> /etc/clamav/clamd.conf ;
	
	echo -e "\n ... check for cgi-bin on drive" ;
	
		if [[ ! "$(cat /etc/apache2/sites-available/000-default.conf | grep cgi-bin)" =~ '/usr/lib/cgi-bin/' ]] ;
	then
		mkdir -p /usr/lib/cgi-bin/ 2>/dev/null ;
		echo -e "\nScriptAlias /cgi-bin/ /usr/lib/cgi-bin/\r
		<Directory "/usr/lib/cgi-bin">\r
		AllowOverride None\r
		Options +ExecCGI +MultiViews +SymLinksIfOwnerMatch\r
		Order allow,deny\r
		Allow from all\r
		</Directory>\n" >> /etc/apache2/sites-available/000-default.conf ;
	else
		echo -e "\n ... cgi-bin dir exists" ;
fi
		echo -e "\n ... update apache2 configuration" ;
		a2enmod cgid && wait ;
		
		echo -e "\n ... restarting apache2 server" ;
		systemctl restart apache2.service && wait ;

		echo -e "\n ... put $SUDO_USER/Downloads in a Jail" ;
		echo "/dev/shm /home/$SUDO_USER/Downloads auto bind 0 0" | tee -a /etc/fstab ;

		echo -e "\n ... set the rights for installed (to remove it later)" ;
		chown $SUDO_USER:$SUDO_USER "/home/$SUDO_USER/.installed" ;

		echo -e "\n ... set the rights for .wH0rUNSon " ;
		touch $HOME/.wH0rUNSon && chown $SUDO_USER:$SUDO_USER $HOME/.wH0rUNSon && chmod 0660 $HOME/.wH0rUNSon ;
		
		# workaround for debconf's snort
		echo -e "\n ... installing snort " ;
		apt-get -f -m -y --allow-change-held-packages install snort && wait ;
		# reconfigure all
		echo -e "\n ... reconfiguring installed packages " ;
		dpkg --configure -a && wait ;
		# add i386 arch in 64bit system, to install wine32
		echo -e "\n ... add i386 arch in 64bit system, to install wine32" ;
		sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get -f -y -m --allow-change-held-packages install wine32 && wait ;
		# update upgrade clean and autoremove
		echo -e "\n ... update upgrade clean and autoremove" ;
		apt-get update && apt-get -f -y -m --allow-change-held-packages upgrade && wait ;
		apt-get clean &&
		apt -f -y -m autoremove &&
		
		echo -e "\n\n ... Congratulations we have min-dev-enviro successfully installed!\r"
		read -p " ... continue?" ;
		echo -e "\n ... RESTART IN 6 SECONDS...\r" ;
		sleep 6 ;
		init 6 ;
else
		echo -e "\n M1N-D3V-3NV1R0 allready installed!\n run this script from within the folder min-dev-enviro\n do: rm /home/$SUDO_USER/.installed\n after installation, system will restart." ;
fi
fi
