#!/bin/bash
# opens PDF from ~/Documents folder
LANG="C" ;
IFS=$(echo -en "\b\n") ;

		if [ -e $1 ] && [[ $(file $1) =~ directory ]] ;
	then
		for open in $(find ~/"${1}"*.pdf -type f | sed 's/\ /\\ /g' | sed 's/(/\(/g' | sed 's/)/\)/g'); 
	do 
		while read line
	do
						mupdf $line 2>/dev/null && wait ;
		done <<<$open;
	done;
	else
		echo -e "\n ... type correctly, opens only in folders" ;
fi
