#!/bin/bash
# mindevenviro serv-if-up
# serv-if-up (daemon) : restarts servers and notify
###     WARNING:    DON'T EDIT ANYTHING BELOW       ###  
LANG="C";
up="0"
		if [ $EUID != 0 ] ;
	then
		echo "Hi $USER, this script restart servers and notify if error and or success" ;
		echo "USAGE: sudo redundanz -m" ;
else
	if [[ "$(ps aux | grep -v grep | grep -v nano | grep redundanz | awk '{print $2}' | wc -l) " -gt "1" ]] ;
then

# temp folder
		if [[ "$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" != '' ]] ; 
	then
		tmpfolder="$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" ;
	else
		tmpfolder="/tmp" ;
fi
# temp folder END

# name vars
nids="snort" ;
antivirus="clamd" ;
webserver="apache2" ;
datenbank="mysql" ;
mta="sendmail" ;
mailer="sendmail" ;
empty02='' ;
noHome="No Home Partition on this computer" ;
WARN01="80" ;
WARN02="85" ;
# name vars END

# temp file in volatile ~/Download
> "$tmpfolder/root_mail_status" ;
# temp file END

# finds connected Iface and saves in vars
findIface(){
		if [[ $up = "0" ]] ;
	then 
		interface="$(cat /proc/net/route | head -n2 | awk '{print $1}' | tail -n1)";
		echo "$interface" > "$tmpfolder"/interface ;
		echo ":: We run this Iface: $interface $(date | awk '{print $1,$3,$4}') ::" > /dev/pts/3 ;
	fi
}
# findIface END

# snortUP
snortUP(){
		if [[ $(ps axu | grep -v grep | grep "$nids") = '' ]] ;
	then
		/etc/init.d/"$nids" start -i "$interface"
		
		if setsid "$nids" -i "$interface" >/dev/null 2>&1 < /dev/null
	then

ps axu | grep -v grep | grep -v snortup | grep "$nids" > "$tmpfolder/root_mail_status" ;
	
cat << EOM | sendmail root@localhost

$(cat "$tmpfolder/root_mail_status")

EOM

else

cat << EOM | sendmail root@localhost

$(cat "$tmpfolder/root_mail_status")

EOM

fi
	else
		sleep 0.1 ;
fi
}
# snortUP END

# checks if clamd is up, if false restarts
clamdUP(){
	 /etc/init.d/"$antivirus" stop ;
	if /etc/init.d/"$antivirus" start > "$tmpfolder/root_mail_status" ;
then

/etc/init.d/"$antivirus" status >> "$tmpfolder/root_mail_status" ;

echo "$?" >> "$tmpfolder/root_mail_status" ;

echo ":: $antivirus fails, but restartet successfully, you got an email $(date | awk '{print $1,$3,$4}') ::" > /dev/pts/3

cat << EOM | sendmail root@localhost

$(cat "$tmpfolder/root_mail_status")

EOM

	else

/etc/init.d/"$antivirus" status > "$tmpfolder/root_mail_status" ;
date "+Start Attempt $antivirus, Failure Time: %H.%M" >> "$tmpfolder/root_mail_status" ;

cat << EOM | sendmail root@localhost

$(cat "$tmpfolder/root_mail_status")

EOM

echo ":: you got email, $antivirus fails, cannot restart $(date | awk '{print $1,$3,$4}') ::" > /dev/pts/3 ;

fi
}
# clamdUP END

# checks if apache2 is up, if false restarts
apacheUP(){
	/etc/init.d/"$webserver" stop ;
	if /etc/init.d/"$webserver" start > "$tmpfolder/root_mail_status" ;
then

/etc/init.d/"$webserver" status >> "$tmpfolder/root_mail_status" ;

echo "$?" >> "$tmpfolder/root_mail_status" ;

echo ":: $webserver fails, but restartet successfully, you got an email $(date | awk '{print $1,$3,$4}') ::" > /dev/pts/3

cat << EOM | sendmail root@localhost

$(cat "$tmpfolder/root_mail_status")

EOM

	else

/etc/init.d/"$webserver" status > "$tmpfolder/root_mail_status" ;
date "+Start Attempt $webserver, Failure Time: %H.%M" >> "$tmpfolder/root_mail_status" ;

cat << EOM | sendmail root@localhost

$(cat "$tmpfolder/root_mail_status")

EOM

echo ":: you got email, $webserver fails, cannot restart $(date | awk '{print $1,$3,$4}') ::" > /dev/pts/3 ;

fi
}
# apacheUP END

# sendmailUP checks if sendmail is up, if false restarts
sendmailUP(){
checkprog2=$(whereis "$mta" | awk '{print $2}') ;
/etc/init.d/"$mta" stop ;
	if [[ -e $checkprog2 ]] && /etc/init.d/"$mta" start > "$tmpfolder/root_mail_status" ;
then
	/etc/init.d/"$mta" status >> "$tmpfolder/root_mail_status" ;

	echo "$?" >> "$tmpfolder/root_mail_status" ;

cat << EOM | sendmail root@localhost

$(cat "$tmpfolder/root_mail_status")

EOM

echo ":: $mta is accepting connections again, you got an email $(date | awk '{print $1,$3,$4}') ::" > /dev/pts/3 ;

	else

	/etc/init.d/"$mta" status  > "$tmpfolder/root_mail_status" ;
	date "+Start Attempt $mta, Failure Time: %H.%M" >> "$tmpfolder/root_mail_status" ;

cat << EOM | sendmail root@localhost

$(cat "$tmpfolder/root_mail_status")

EOM

echo ":: you got email, $mta cannot restart $(date | awk '{print $1,$3,$4}') ::" > /dev/pts/3 ;

fi
}
# sendmailUP END

# mysqlUP checks if mysql is up, if false restarts
mysqlUP(){
/etc/init.d/"$datenbank" stop ;
	if /etc/init.d/"$datenbank" start > "$tmpfolder/root_mail_status" ;
then
	/etc/init.d/"$datenbank" status >> "$tmpfolder/root_mail_status" ;

	echo "$?" >> "$tmpfolder/root_mail_status" ;

cat << EOM | sendmail root@localhost

$(cat "$tmpfolder/root_mail_status")

EOM

echo ":: $datenbank is accepting connections again, you got an email $(date | awk '{print $1,$3,$4}') ::" > /dev/pts/3 ;

	else

	/etc/init.d/"$datenbank" status > "$tmpfolder/root_mail_status" ;
	date "+Start Attempt $datenbank, Failure Time: %H.%M" >> "$tmpfolder/root_mail_status" ;

cat << EOM | sendmail root@localhost

$(cat "$tmpfolder/root_mail_status")

EOM

echo ":: you got email, $datenbank cannot restart $(date | awk '{print $1,$3,$4}') ::" > /dev/pts/3 ;

fi
}
# mysqlUP END

# checkfreeSpace check for drive space and notify if over limit
checkfreeSpace(){
IFHOMEEXIST=$(df -h | grep -E /home$) ;
SIZEONHOME=$(df -h | grep -E /home$ | awk '{print $2}') ;
SIZEON=$(df -h | grep -E /$ | awk '{ print $2 }') ;
USEDON=$(df -h | grep -E /$ | awk '{ print $3 }') ;
INODES=$(df -i | grep -E /$ | awk '{ print $2 }') ;
FREEINODES=$(df -i | grep -E /$ | awk '{ print $4 }') ;

	if [[ "$IFHOMEEXIST" = '' ]] ;
then
	PERCENTUSED01=$noHome ;
fi

cat << EOM | sendmail root@localhost

Subject:running_out_of_disk_space

_________________________________________________
/


redundanz: On host $(uname -n) :: ;

Warn percentage on /: $WARN01 %

Used percentage on the root@localhost /: $PERCENTUSED01

Inodes on host $(uname -n): $INODES

Size on /: $SIZEON GB

Used Inodes on /: $USEDON .

Free Inodes on host $(uname -n): $FREEINODES



_________________________________________________
/home


Warn percentage on /home: $WARN02 %

Used percentage on /home: $PERCENTUSED01

Size on /home: $SIZEONHOME GB

EOM

echo "::WARNING:: your over $WARN01 % or $WARN02 %, you got email $(date | awk '{print $1,$3,$4}') ::" > /dev/pts/3 ;

}
# END checking free space

# loop
		while true
	do
		if [[ $(netstat -ar) =~ 'default' ]] ;
	then 
		findIface && wait && sleep .5 ;
		up="1" ;
	else

echo ":: We got no Internet $(date | awk '{print $1,$3,$4}') ::" > /dev/pts/3 ;

		up="0" ;

cat << EOM | sendmail root@localhost

Subject:down

We got no Internet.

EOM
	fi
		if [[ "$(ps aux | grep -v grep | grep snort)" = '' ]] ;
	then
		snortUP && wait && sleep .5 ;
	fi
		if [[ "$(ps aux | grep -v grep | grep clamd)" = '' ]] ;
	then
		clamdUP && wait && sleep .5 ;
	fi
        if [[ "$(netstat -an | grep LISTEN | grep :80 | awk '{print $4}' | tail -n1)" = '' ]] ;
	then
		apacheUP && wait && sleep .5 ;
	fi
        if [[ "$(netstat -an | grep LISTEN | grep :25 | awk '{print $4}' | tail -n1)" = '' ]] ;
	then
		sendmailUP && wait && sleep .5 ;
	fi
        if [[ "$(netstat -an | grep LISTEN | grep :3306 | awk '{print $4}' | tail -n1)" = '' ]] ;
	then
		mysqlUP && wait && sleep .5 ;
	fi
		if [[ "$WARN01" -lt "$(df -h | grep -E /$ | awk '{ print $5 }' | sed -n 's/%//p')" ]] || [[ "$WARN02" -lt "$(df -h | grep -E /home$ | awk '{ print $5 }' | sed -n 's/%//p')" ]] ;
	then
		checkfreeSpace && wait && sleep .5 ;
	fi
done
# loop end
fi
fi
# END
