#!/bin/bash
# serv-if-up: restarts servers and notify
#

		if [ $EUID != 0 ] ;
	then
		echo "Hi $USER, this script restart servers and notify if error and or success" ;
		echo "USAGE: sudo redundanz -m" ;
else

	if [[ "$(ps aux | grep -v grep | grep -v nano | grep redundanz | awk '{print $2}' | wc -l) " -gt "1" ]] ;
then

# temp folder
		if [[ "$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" != '' ]] ; 
	then
		tmpfolder="$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" ;
	else
		tmpfolder="/tmp" ;
fi
# temp folder END

interface='' ;

LANG="C";

nids="snort" ;

antivirus="clamd" ;

webserver="apache2" ;

datenbank="mysql" ;

mta="sendmail" ;

mailer="sendmail" ;

empty02='' ;

nohomePartition="No Home Partition on this computer" ;

WARN01="80" ;

WARN02="85" ;

> $tmpfolder/root_mail_status ;

while true

do
sleep 0.1 ;

		if [[ ! $(cat /proc/net/route | head -n2 | awk '{print $1}' | tail -n1) =~ 'Iface' ]] ;
	then
		if [[ "$interface" = '' ]]
	then
		interface="$(cat /proc/net/route | head -n2 | awk '{print $1}' | tail -n1)";
		echo ":: We run this Iface: $interface ::" > /dev/pts/3 ;
		date > /dev/pts/3 ;
	fi
	else

interface='' ;
echo ":: We got no Internet ::" > /dev/pts/3 ;
date > /dev/pts/3 ;

cat << EOM | sendmail root@localhost

Subject:down

We got no Internet.

EOM

fi

checknids=$(ps aux | grep -v grep | grep snort) ;

	if [[ "$checknids" = '' ]];
then
		sleep 0.1 ;
		
		if [[ $(ps axu | grep -v grep | grep -v snortup | grep "$nids") = '' ]] ;
	then
		/etc/init.d/$nids start -i $interface
		
		if setsid $nids -i $interface >/dev/null 2>&1 < /dev/null
	then

ps axu | grep -v grep | grep -v snortup | grep "$nids" > $tmpfolder/root_mail_status ;
	
cat << EOM | sendmail root@localhost

$(cat $tmpfolder/root_mail_status)

EOM

else

cat << EOM | sendmail root@localhost

$(cat $tmpfolder/root_mail_status)

EOM

fi
	else
		sleep 0.1 ;
	fi
fi

checkantivirus=$(ps aux | grep -v grep | grep clamd) ;

        if [[ "$checkantivirus" = '' ]];
then
	systemctl stop "$antivirus".service ;
	sleep 0.1 ;

	if systemctl start "$antivirus".service > $tmpfolder/root_mail_status ;
then

systemctl status "$antivirus".service >> $tmpfolder/root_mail_status ;

echo "$?" >> $tmpfolder/root_mail_status ;

echo ":: $antivirus fails, but restartet successfully, you got an email ::" > /dev/pts/3

date > /dev/pts/3

cat << EOM | sendmail root@localhost

$(cat $tmpfolder/root_mail_status)

EOM

	else

systemctl status "$antivirus".service > $tmpfolder/root_mail_status ;
date "+Start Attempt $antivirus, Failure Time: %H.%M" >> $tmpfolder/root_mail_status ;

cat << EOM | sendmail root@localhost

$(cat $tmpfolder/root_mail_status)

EOM

echo ":: you got email, $antivirus fails, cannot restart ::" > /dev/pts/3 ;

date > /dev/pts/3 ;

	fi
fi

checkport80=$(netstat -an | grep LISTEN | grep :80 | awk '{print $4}' | tail -n1) ;

        if [[ "$checkport80" = '' ]];
then
	systemctl stop "$webserver".service ;
	sleep 0.2 ;
	if systemctl start "$webserver".service > $tmpfolder/root_mail_status ;
then

systemctl status "$webserver".service >> $tmpfolder/root_mail_status ;

echo "$?" >> $tmpfolder/root_mail_status ;

echo ":: $webserver fails, but restartet successfully, you got an email ::" > /dev/pts/3

date > /dev/pts/3

cat << EOM | sendmail root@localhost

$(cat $tmpfolder/root_mail_status)

EOM

	else

systemctl status "$webserver".service > $tmpfolder/root_mail_status ;
date "+Start Attempt $webserver, Failure Time: %H.%M" >> $tmpfolder/root_mail_status ;

cat << EOM | sendmail root@localhost

$(cat $tmpfolder/root_mail_status)

EOM

echo ":: you got email, $webserver fails, cannot restart ::" > /dev/pts/3 ;

date > /dev/pts/3 ;

	fi
fi

checkport25=$(netstat -an | grep LISTEN | grep :25 | awk '{print $4}' | tail -n1) ;

        if [[ "$checkport25" = '' ]];
then

checkprog2=$(whereis "$mta" | awk '{print $2}') ;
systemctl stop "$mta".service ;
sleep 0.2 ;

	if [[ -e $checkprog2 ]] && systemctl start "$mta".service > $tmpfolder/root_mail_status ;
then
	systemctl status "$mta".service >> $tmpfolder/root_mail_status ;

	echo "$?" >> $tmpfolder/root_mail_status ;

cat << EOM | sendmail root@localhost

$(cat $tmpfolder/root_mail_status)

EOM

echo ":: $mta is accepting connections again, you got an email ::" > /dev/pts/3 ;

date > /dev/pts/3 ;

	else

	systemctl status "$mta".service > $tmpfolder/root_mail_status ;
	date "+Start Attempt $mta, Failure Time: %H.%M" >> $tmpfolder/root_mail_status ;

cat << EOM | sendmail root@localhost

$(cat $tmpfolder/root_mail_status)

EOM

echo ":: you got email, $mta cannot restart ::" > /dev/pts/3 ;

date > /dev/pts/3 ;

	fi
fi

checkport3306=$(netstat -an | grep LISTEN | grep :3306 | awk '{print $4}' | tail -n1) ;

        if [[ "$checkport3306" = '' ]];
then

/etc/init.d/"$datenbank" stop ;
sleep 0.2 ;

	if /etc/init.d/"$datenbank" start > $tmpfolder/root_mail_status ;
then
	/etc/init.d/"$datenbank" status >> $tmpfolder/root_mail_status ;

	echo "$?" >> $tmpfolder/root_mail_status ;

cat << EOM | sendmail root@localhost

$(cat $tmpfolder/root_mail_status)

EOM

echo ":: $datenbank is accepting connections again, you got an email ::" > /dev/pts/3 ;

date > /dev/pts/3 ;

	else

	/etc/init.d/"$datenbank" status > $tmpfolder/root_mail_status ;
	date "+Start Attempt $datenbank, Failure Time: %H.%M" >> $tmpfolder/root_mail_status ;

cat << EOM | sendmail root@localhost

$(cat $tmpfolder/root_mail_status)

EOM

echo ":: you got email, $datenbank cannot restart ::" > /dev/pts/3 ;

date > /dev/pts/3 ;

	fi
fi

sleep 0.5 ;
# check for drive space and notify if over limit
PERCENTUSED01=$(df -h | grep -E /$ | awk '{ print $5 }' | sed -n 's/%//p') ;

PERCENTUSED02=$(df -h | grep -E /home$ | awk '{ print $5 }' | sed -n 's/%//p') ;

IFHOMEEXIST=$(df -h | grep -E /home$) ;

SIZEONHOME=$(df -h | grep -E /home$ | awk '{print $2}') ;

SIZEON=$(df -h | grep -E /$ | awk '{ print $2 }') ;

USEDON=$(df -h | grep -E /$ | awk '{ print $3 }') ;

INODES=$(df -i | grep -E /$ | awk '{ print $2 }') ;

FREEINODES=$(df -i | grep -E /$ | awk '{ print $4 }') ;
# END checking free space

if [[ "$WARN01" -lt "$PERCENTUSED01" ]] || [[ "$WARN02" -lt "$PERCENTUSED02" ]] ;

then

if [[ "$IFHOMEEXIST" = '' ]] ;

then

PERCENTUSED02="$nohomePartition" ;

fi

cat << EOM | sendmail root@localhost

Subject:running_out_of_disk_space

_________________________________________________
/


redundanz: On host $(uname -n) :: ;

Warn percentage on /: $WARN01 %

Used percentage on the root@localhost /: $PERCENTUSED01

Inodes on host $(uname -n): $INODES

Size on /: $SIZEON GB

Used Inodes on /: $USEDON .

Free Inodes on host $(uname -n): $FREEINODES



_________________________________________________
/home


Warn percentage on /home: $WARN02 %

Used percentage on /home: $PERCENTUSED02

Size on /home: $SIZEONHOME GB

EOM

echo "::WARNING:: your over $WARN01 % or $WARN02 %, you got email::" > /dev/pts/3 ;
date > /dev/pts/3 ;

fi
done
rm -f $tmpfolder/root_mail_status
fi
fi
