#!/bin/bash
# sets the root password for mariadb

###     WARNING:    DON'T EDIT ANYTHING BELOW       ###

		printf "enter your mysql root password: "; read mysqlnewpass ;
		printf "enter a password for mysql plugin: "; read mysql_native_pass ;
	
		if	[[ "$mysqlnewpass" != '' ]] && [[ "$mysql_native_pass" != '' ]] ;
	then
		if grep socket /etc/mysql/my.cnf && exitcode=$(echo $?)
	then
		if [[ $exitcode = 1 ]] ;
	then
		echo "socket = ">>/etc/mysql/my.cnf ;
		sed -i 's/\(socket *= *\).*/\1''/g' /etc/mysql/my.cnf ;
	fi
fi
		mysqlconn="mysql -u root" ;
		mysqld_safe --skip-grant-tables &
		$mysqlconn -e "use mysql; update user set password=PASSWORD("$mysqlnewpass") where User='root';"
		$mysqlconn -e "use mysql; update user set plugin="$mysql_native_pass";"
		$mysqlconn -e "use mysql; FLUSH PRIVILEGES;"
		echo -e "\n ... update mysql root passwords" ;
		sed -i "s/\(p4SSWORD *= *\).*/\1$mysqlnewpass/" /etc/mysql_cp_db_password.conf ;
		echo -e "\n ... restarting mysql-server" ;
		/etc/init.d/mysql reload ;
		/etc/init.d/mysql restart ;
	fi		
