#!/bin/bash
# mindevenviro set_mysql_passwd
# sets the root password for mariadb
###     WARNING:    DON'T EDIT ANYTHING BELOW       ###
# 
LANG=C ;
		if [ $EUID != 0 ] ;
	then
		echo "please sudo"
		exit 0 ;
	else
		mysqlconn="sudo -u root mysql -u root" ;
help(){
shift 0 ;
echo -e "hello $SUDO_USER\nset new mariadb root password\n" ;
echo -e "Usage: $0 [--password] [--help]\r" ;
exit 0 ;
}		

stop_mysql(){
		for tokill in $(ps aux | grep -v grep | grep -v set_mysql_passwd | grep mysql | awk '{print $2}') ;
	do
		sudo kill -15 "$tokill" 2>/dev/null
	done
	}

changepass(){
		if	[[ "$mysqlnewpass" != '' ]] ;
	then
		stop_mysql ;
		echo "starting mysql to maintenance" ;
		mysqld_safe --skip-grant-tables &
		sleep 3 ;
		$mysqlconn -e "use mysql; update mysql.user set password=password('$mysqlnewpass') where user='root';"
		$mysqlconn -e "use mysql; update mysql.user set plugin='' where user='root';"
		$mysqlconn -e "use mysql; FLUSH PRIVILEGES;"
		stop_mysql ;
		echo -e "\n ... update mysql root passwords" ;
		sed -i "s/\(p4SSWORD *= *\).*/\1$mysqlnewpass/" /etc/mysql_cp_db_password.conf ;
		sed -i "s/\(plugin_password *= *\).*/\1/" /etc/mysql_cp_db_password.conf ;
		mysqld_safe &
		echo " done !" ;
	fi	
}

# ASK 
  case "$1" in
   --password)
		REPLY="set"
		shift
      ;;
   --help)
		REPLY="help"
		shift
		help ;
      ;; 
  esac

		if [[ "$REPLY" = "set" ]] ;
	then
		killall -15 redundanz 2>/dev/null ;
		echo -e "\n - redundanz is down, you should start again.\n"
		printf "enter your mysql root password: "; read mysqlnewpass ;
		changepass "$@" ;
		
		elif [[ "$REPLY" = "help" ]] ;
	then
		help ;
	else
		echo "Try 'sudo $0 --help' for more information."
		exit 0 ;
	fi
fi
