#!/bin/bash
# sets the root password for mariadb

###     WARNING:    DON'T EDIT ANYTHING BELOW       ###

LANG=C ;
set -x
		if [ $EUID != 0 ] ;
	then
		sudo "$0" ;
	else
		mysqlconn="mysql -u root --no-defaults" ;
help(){
shift 0 ;
echo -e "hello $SUDO_USER\nset new mariadb root password\n" ;
echo -e "Usage: $0 [--password] [--help]\r" ;
exit 0 ;
}		

changepass(){	
		if	[[ "$mysqlnewpass" != '' ]] ;
	then
		ps aux | grep -v grep | grep mysql | head -n1 | awk '{print $2}' | xargs kill -9 2>/dev/null;
		ps aux | grep -v grep | grep mysqld_safe | head -n1 | awk '{print $2}' | xargs kill -9 2>/dev/null;
		sudo mknod /run/mysqld/mysqld.sock p ;
		mysqld_safe --skip-grant-tables &
		$mysqlconn -e "use mysql; update mysql.user set password=password('$mysqlnewpass') where user='root';" && wait ;
		$mysqlconn -e "use mysql; update mysql.user set plugin='' where user='root';" && wait ;
		$mysqlconn -e "use mysql; FLUSH PRIVILEGES;" && wait ;
		ps aux | grep -v grep | grep mysqld_safe | head -n1 | awk '{print $2}' | xargs kill -9 2>/dev/null;
		echo -e "\n ... update mysql root passwords" ;
		sed -i "s/\(p4SSWORD *= *\).*/\1$mysqlnewpass/" /etc/mysql_cp_db_password.conf ;
		sed -i "s/\(plugin_password *= *\).*/\1/" /etc/mysql_cp_db_password.conf ;
		echo -e "\n ... hit enter" ;
		/etc/init.d/mysql start && wait ;
		echo -e "\n ... hit enter" ;
	fi		
}

# ASK
  case "$1" in
   --password)
		REPLY="set"
		shift
      ;;
   --help)
		REPLY="help"
		shift
		help ;
      ;; 
  esac

		if [[ "$REPLY" = "set" ]] ;
	then
		printf "enter your mysql root password: "; read mysqlnewpass ;
		changepass ;
		
		elif [[ "$REPLY" = "help" ]] ;
	then
		help ;
	else
		echo "please sudo this script."
		echo "Try 'sudo $0 --help' for more information."
		exit 0 ;
	fi
fi
