#!/bin/bash

# runs on systems with systemd, WITHOUT network-managers,
# you must have a running version of both: ClamAV and Snort.
# Changes your MAC-ADDRESS and does a list of usable and not 
# usable MAC-ADDRESSES in $HOME. Puts interface down if clamd 
# or snort fails and changes the MAC again. ctrl+C cut's Ethernet Interface 
# connection and revert to your vendors MAC-ADDRESS.

###     WARNING:    DON'T EDIT ANYTHING BELOW       ###

LANG="C" ;
IFS=$(echo -en "\n\b") ;

		if [ ! $EUID = 0 ] ;
	then
		sudo "$0" ;
else
		if [[ $(cat /proc/net/route | head -n2 | awk '{print $1}' | tail -n1) = Iface ]] ;
	then
		echo "you must connect to the internet, I'm sorry." ;
		exit 0
fi

# temp folder
		if [[ "$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" != '' ]] ;
	then
		tmpfolder="$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" ;
	else
		tmpfolder="/tmp" ;
fi
# temp folder END

# vendors mac-address
		if [ ! -e "/home/root/.vendorsmac" ] ;
	then
		touch /home/root/.vendorsmac ;
		chmod 0660 /home/root/.vendorsmac ;
		
		if ip link show | grep ether | awk '{print $2}' | tee -a /home/root/.vendorsmac ;
	then
		echo "installed" ;
	fi
fi
# vendors mac-address END

clear && echo -e "\n" ;
nnumberr="0" ;
cat /proc/net/route | head -n2 | awk '{print $1}' | tail -n1 >| "$tmpfolder"/interface && wait ;
interface="$(cat "$tmpfolder"/interface)" ;

		if [[ "$interface" =~ eno|eth ]] ;
	then
		whoUP="1" ;

		elif [[ "$interface" =~ wl|wi ]] ;
	then
		whoUP="2" ;
	else
		whoUP="none" ;
fi

stop_network(){
	#
	ip link set dev "$interface" down ; sleep 2 ;
}

puffeRR(){
		if [[ "$(cat /home/root/.vendorsmac | head -n"${whoUP}" | tail -n1)" = "$(ip link show | grep ether | awk '{print $2}')" ]] ;
	then
		echo -e "\n -shi3lD: shut down interfaces?\n " ;
		read -p " enter to continue" ;
		stop_network ;		
		echo -e "\n :: changing macaddress :: \n"  
		source start_shield ;	
fi
}

exitHandler(){
echo " -"
printf " quit? (y/n) " ; read -r
echo " -"
		if [[ $REPLY =~ y|Y|j|J ]] ;
	then
		ip link set dev "$interface" down && sleep 2 &&
		ip link set dev "$interface" address "$(cat /home/root/.vendorsmac | head -n"${whoUP}" | tail -n1)" &&
		ip link set dev "$interface" up && sleep 2 ;
		echo -e "\n .You where surfing with this MAC:\n\n
		$(find /home/root/* -name "*mac_recieves_dhcp_lease*" | grep "$(date | \
		awk '{print $2,$6}' | sed 's/\ //g')" | xargs cat | tail -n1)\n" ;
		exit 0 ;

		elif [[ $REPLY =~ n|N ]] ;
	then
		return ;
fi
}
		spin='.oOo' ; i=0 ;
		spin2='-\|/' ;

		while trap 'exitHandler' SIGINT ;
	do
		if [[ ! "$(ip link show "$interface" | grep ether | awk '{print $2}')" =~ "$(cat /home/${SUDO_USER}/.vendorsmac)" ]] ;
	then		
		while true
	do
		((nnumberr++)) ;
		i=$(( (i+1) %4 )) ; printf "\r ${spin2:$i:1} UPTIME:$nnumberr${spin:$i:1} " ; sleep .1 ;
	done
		
	else
		puffeRR ;
	fi
done
fi
