#!/bin/bash
# mindevenviro shi3lD
# Changes your MAC-ADDRESS and do a list of usable and not usable MAC-ADDRESSES in $HOME.
# restart clamd and snort if failure, cut the Ethernet Interface connection, while starting up
# ctrl+C cut's Ethernet Interface connection and revert to your vendors MAC-ADDRESS
###     WARNING:    DON'T EDIT ANYTHING BELOW       ###  
LANG="C" ;
FILE_m="serv-if-up" ;

		if [ ! $EUID = 0 ] ;
	then
		echo -e " USAGE: sudo $0 \n depends on redundanz" ;
		exit 0 ;
else
		if [[ "$(ps aux | grep "$FILE_m" | grep -v nano | grep -v geany | grep -v grep | tail -n1) " != "1" ]] ;
	then

clear && echo -e "\n" ;
nnumberr="0" ;
# temp folder
		if [[ "$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" != '' ]] ; 
	then
		tmpfolder="$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" ;
	else
		tmpfolder="/tmp" ;
fi
# temp folder END
interface="$(cat "$tmpfolder"/interface)" ;
#

		if [[ "$interface" =~ eno|eth ]] ;
	then
		whoUP="1" ;

		elif [[ "$interface" =~ wl|wi ]] ;
	then
		whoUP="2" ;
	else
		whoUP="none" ;
fi

puffeRR(){
		if [[ "$(netstat -ar)" =~ 'default' ]] ;
	then
		source stop_shield ;
	else
		clear;
		echo -e "\n ::    D A N G E R      ::" ;
		echo -e "\n :: changing macaddress :: \n" &&
		source start_shield ;
	fi
}

exitHandler(){

		echo -e "-"
		printf " quit? (y/n) " ; read
		echo -e "-"

			if [[ $REPLY =~ y|Y|j|J ]] ;
		then
			sudo ip link set dev "$interface" down && sleep 5 && 
			sudo ip link set dev "$interface" address "$(cat /root/.vendorsmac | head -n"${whoUP}" | tail -n1)" && 
			sudo ip link set dev "$interface" up && sleep 2 ;
			echo -e "\n .You where surfing with this MAC:\n\n
			$(find /home/"$SUDO_USER"/* -name "*mac_recieves_dhcp_lease*" | grep "$(date | \
			awk '{print $2,$6}' | sed 's/\ //g')" | xargs cat | tail -n1)\n" ;
			exit 0 ;

			elif [[ $REPLY =~ n|N ]] ;
		then
			return ;
	fi
}
		while trap 'exitHandler' SIGINT ;
	do
		if [[ "$(ps aux | grep -E -i -w 'snort|clamd' | grep -v grep | awk '{print $11}' | grep -E 'snort|clamd' | \
		wc -l | tr -d ' ')" = "2" ]] && [[ "$(ip link show "$interface" | grep ether | awk '{print $2}')" != "$(cat /root/.vendorsmac | head -n"${whoUP}" | tail -n1)" ]] ;
	then
		spin='.oOo' ; i=0 ;
		spin2='-\|/' ;

		while [[ "$(ps aux | grep -E -i -w 'snort|clamd' | grep -v grep | awk '{print $11}' | grep -E 'snort|clamd' | \
		wc -l | tr -d ' ')" = "2" ]] && [[ "$(ip link show "$interface" | grep ether | awk '{print $2}')" != "$(cat /root/.vendorsmac | head -n"${whoUP}" | tail -n1)" ]] ;
	do
		((nnumberr++));
		i=$(( (i+1) %4 )) ; printf "\r ${spin2:$i:1} UPTIME:$nnumberr${spin:$i:1} " ; sleep .1 ;
	done
	else
		puffeRR ;
	fi
done
else
	clear ;
	printf "warning your system could heat up, do you want to reboot? ok|no " ; read -r ;
	
		if [[ "$REPLY" = "ok" ]] ;
	then
		stop_shield && init 6 ;
	else
		echo "do you know?"
fi
fi
fi
