#!/bin/bash
# start port scanner

		if [[ $EUID != 0 ]] ;
	then
		echo -e "\n please sudo this" ;
	else
		/etc/init.d/snort start -i wlp3s0b1 &
		setsid snort -i wlp3s0b1 >/dev/null 2>&1 < /dev/null &
		sleep 3 ;
		exit 0 ;
fi
