#!/bin/bash
# depends on shi3lD
###     WARNING:    DON'T EDIT ANYTHING BELOW       ###

LANG="C" ;
IFS=$(echo -en "\n\b") ;

		if [ ! $EUID = 0 ] ;
	then
		sudo "$0" ;
else
	if [[ "$(ps aux | grep -v grep | grep -v nano | grep shi3lD | awk '{print $2}' | wc -l) " -gt "1" ]] ;
then

stopLoop="0" ;
binarie0="/usr/sbin/clamd" ;
binarie1="/usr/sbin/snort" ;
homeordner="/home/${SUDO_USER}/" ;
cat /proc/net/route | head -n2 | awk '{print $1}' | tail -n1 >| "$tmpfolder"/interface ;
interface="$(cat "$tmpfolder"/interface)" ;
nnumberOFinterface="$(echo "$interface" | wc -w | tr -d ' ')" ;

puff_MACs(){
		if [[ "$(cat /home/"$SUDO_USER"/.vendorsmac)" = "$(ip link show | grep ether | awk '{print $2}')" ]] ;
	then
		until [[ "$nnumberOFinterface" = "0" ]] ;
	do
		echo -e "puffing MACs ...\n" ;
		m4c=$(echo "$interface" | awk '{print $'"$nnumberOFinterface"'}') &&
		newM4CnewM4C=$(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//') &&
		ip link set dev "$m4c" address "$newM4CnewM4C" && sleep 3 &&
		ip link set dev "$m4c" up &&
		((nnumberOFinterface--)) &&
		sleep 9 ;
done
fi
}

start_s(){
		if [[ $(ps aux | grep snort | grep -v grep | grep -v nano | awk '{print $11}') = "$binarie0" ]]
	then
		echo -e "snort is allready running ...\n" ;
	else
		#chmod o+r /dev/bpf*;
		systemctl restart snort.service && echo -e "snort is running ...\n" ;
		sleep 2 ;
fi
}

start_c(){
		if [[ $(ps aux | grep clamd | grep -v grep | grep -v nano | awk '{print $11}') = "$binarie1" ]]
	then
		echo -e "clamd is allready running ...\n" ;
	else
		#mknod -F native /dev/clamauth c 3 2 ;
		systemctl restart clamav-daemon.service && echo -e "clamd is running ...\n" ;
		sleep 2 ;
fi
}

writeM4C_Connected(){
		if [[ -e "${homeordner}$(date | awk '{print $2,$6}' | sed 's/\ //g').mac_recieves_dhcp_lease" ]]
	then
		echo -e "$(ip link show "$m4c" | grep ether | awk '{print $2}') :: surf started at: $(date | \
		awk '{print $1, $2, $3, $4, $6}' | sed 's/\ /::/g') -" >> "${homeordner}$(date | awk '{print $2,$6}' | \
		sed 's/\ //g').mac_recieves_dhcp_lease" ;
	else
		touch "${homeordner}$(date | awk '{print $2,$6}' | sed 's/\ //g').mac_recieves_dhcp_lease" && permissions ;
		echo -e "$(ip link show "$m4c" | grep ether | awk '{print $2}') :: surf started at: $(date | \
		awk '{print $1, $2, $3, $4, $6}' | sed 's/\ /::/g') -" >> "${homeordner}$(date | awk '{print $2,$6}' | \
		sed 's/\ //g').mac_recieves_dhcp_lease" ;
fi
}

writeM4C_SelfAssigned(){
		if [[ -e "${homeordner}$(date | awk '{print $2,$6}' | sed 's/\ //g').mac_no_dhcp_lease" ]]
	then
		echo -e "$(ip link show "$m4c" | grep ether | awk '{print $2}') :: surf started at: $(date | \
		awk '{print $1, $2, $3, $4, $6}' | sed 's/\ /::/g') -" >> "$homeordner$(date | awk '{print $2,$6}' | \
		sed 's/\ //g').mac_no_dhcp_lease" ;
	else
		touch "${homeordner}$(date | awk '{print $2,$6}' | sed 's/\ //g').mac_no_dhcp_lease" && permissions ;
		echo -e "$(ip link show "$m4c" | grep ether | awk '{print $2}') :: surf started at: $(date | \
		awk '{print $1, $2, $3, $4, $6}' | sed 's/\ /::/g') -" >> "$homeordner$(date | awk '{print $2,$6}' | \
		sed 's/\ //g').mac_no_dhcp_lease" ;
fi
}

ifUPAntiVirusFireWall(){
		until [[ $(ps aux | grep -E -i -w 'snort|clamd' | grep -v grep | awk '{print $11}' | wc -l | tr -d ' ') = "2" ]] ;
	do
		ifDown0=$(ps aux | grep -vE "grep" | grep -v nano | grep clamd | awk '{print $11}') ;
		ifDown1=$(ps aux | grep -vE "grep" | grep -v nano | grep snort | awk '{print $11}') ;

		if [[ "$ifDown0" != "$binarie0" ]]
	then
		echo -e "restarting ClamAV ...\n" ;
		start_c && return ;
	fi
	    if [[ "$ifDown1" != "$binarie1" ]]
	then
		echo -e "restarting Snort ...\n" ;
		start_s && return ;
	fi
done
}

m41N__(){
		while [[ $stopLoop != "1" ]]
	do
		puff_MACs && ifUPAntiVirusFireWall ;

		if [[ $(netstat -ar) =~ 'default' ]] ; # looks in the routing table for an internet connection
    then
        clear ;
        echo -e "\n - WE HAVE shi3lD ::\n" ;
        echo -e " \
        done ! we go throught $(netstat -ar | grep -vE "grep" | grep default | awk '{print $2}') \n\n \
        $(ip route | grep -vE "grep" | grep src) \n\n \
        and $m4c has now this MAC-Address: $(ip link show "$m4c" | grep ether | awk '{print $2}')\n" ;
        writeM4C_Connected ;
	stopLoop="1" ;
	sudo -u "$SUDO_USER" firefox-esr 2>&1 < /dev/null &
    else
        echo -e "no connection with this $(ip link show "$m4c" | grep ether | awk '{print $2}'), I try again ..."
        . /usr/local/bin/stop_shield ;
	writeM4C_SelfAssigned ;
	fi
done
}
	m41N__ ;
fi
fi
