#!/bin/bash
# depends on shi3lD
###     WARNING:    DON'T EDIT ANYTHING BELOW       ###

LANG="C" ;
IFS=$(echo -en "\n\b") ;

		if [ ! $EUID = 0 ] ;
	then
		sudo "$0" ;
else

# temp folder
		if [[ "$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" != '' ]] ; 
	then
		tmpfolder="$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" ;
	else
		tmpfolder="/tmp" ;
fi
# temp folder END

	if [[ "$(ps aux | grep -v grep | grep -E -i -w 'shi3lD|serv-if-up' | awk '{print $11}' | wc -l | tr -d ' ') " -ge "2" ]] ;
then

stopLoop="0" ;
binarie0="/usr/sbin/clamd" ;
binarie1="/usr/sbin/snort" ;
homeordner="/home/root/" ;
interface="$(cat "$tmpfolder"/interface)" ;
nnumberOFinterface="$(echo "$interface" | wc -w | tr -d ' ')" ;

		if [[ "$interface" =~ eno|eth ]] ;
	then
		whoUP="1" ;

		elif [[ "$interface" =~ wl|wi ]] ;
	then
		whoUP="2" ;
	else
		whoUP="none" ;
fi

puff_MACs(){
		if [[ "$(cat /home/root/.vendorsmac | head -n"${whoUP}" | tail -n1)" = "$(ip link show | grep ether | awk '{print $2}')" ]] ;
	then
		until [[ "$nnumberOFinterface" = "0" ]] ;
	do
		echo -e "puffing MACs ...\n" ;
		m4c=$(echo "$interface" | awk '{print $'"$nnumberOFinterface"'}') &&
		newM4CnewM4C=$(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//') &&
		ip link set dev "$m4c" address "$newM4CnewM4C" && sleep 3 &&
		ip link set dev "$m4c" up &&
		((nnumberOFinterface--)) &&
		sleep 2 ;
done
fi
}

writeM4C_Connected(){
		if [[ -e "${homeordner}$(date | awk '{print $2,$6}' | sed 's/\ //g').mac_recieves_dhcp_lease" ]]
	then
		echo -e "$(ip link show "$m4c" | grep ether | awk '{print $2}') :: surf started at: $(date | \
		awk '{print $1, $2, $3, $4, $6}' | sed 's/\ /::/g') -" >> "${homeordner}.$(date | awk '{print $2,$6}' | \
		sed 's/\ //g').mac_recieves_dhcp_lease" ;
	else
		touch "${homeordner}$(date | awk '{print $2,$6}' | sed 's/\ //g').mac_recieves_dhcp_lease" ;
		echo -e "$(ip link show "$m4c" | grep ether | awk '{print $2}') :: surf started at: $(date | \
		awk '{print $1, $2, $3, $4, $6}' | sed 's/\ /::/g') -" >> "${homeordner}.$(date | awk '{print $2,$6}' | \
		sed 's/\ //g').mac_recieves_dhcp_lease" ;
fi
}

writeM4C_SelfAssigned(){
		if [[ -e "${homeordner}$(date | awk '{print $2,$6}' | sed 's/\ //g').mac_no_dhcp_lease" ]]
	then
		echo -e "$(ip link show "$m4c" | grep ether | awk '{print $2}') :: surf started at: $(date | \
		awk '{print $1, $2, $3, $4, $6}' | sed 's/\ /::/g') -" >> "$homeordner.$(date | awk '{print $2,$6}' | \
		sed 's/\ //g').mac_no_dhcp_lease" ;
	else
		touch "${homeordner}$(date | awk '{print $2,$6}' | sed 's/\ //g').mac_no_dhcp_lease" ;
		echo -e "$(ip link show "$m4c" | grep ether | awk '{print $2}') :: surf started at: $(date | \
		awk '{print $1, $2, $3, $4, $6}' | sed 's/\ /::/g') -" >> "$homeordner.$(date | awk '{print $2,$6}' | \
		sed 's/\ //g').mac_no_dhcp_lease" ;
fi
}

stop_network(){
	#
	ip link set dev "$interface" down ; sleep 2 ;
}

m41N__(){
		while [[ $stopLoop != "1" ]]
	do
		puff_MACs ;

		if [[ $(netstat -ar) =~ 'default' ]] ; # looks in the routing table for an internet connection
    then
        clear ;
        echo -e "\n - WE HAVE shi3lD ::\n" ;
        echo -e " \
        done ! we go throught $(netstat -ar | grep -vE "grep" | grep default | awk '{print $2}') \n\n \
        $(ip route | grep -vE "grep" | grep src) \n\n \
        and $m4c has now this MAC-Address: $(ip link show "$m4c" | grep ether | awk '{print $2}')\n" ;
        writeM4C_Connected ;
		stopLoop="1" ;
    else
        echo -e "no connection with this $(ip link show "$m4c" | grep ether | awk '{print $2}'), I try again ..."
        stop_network ;
		writeM4C_SelfAssigned ;
	fi
done
}
	m41N__ ;
fi
fi
