#!/bin/bash
# mindevenviro stop_shield 
###     WARNING:    DON'T EDIT ANYTHING BELOW	###
LANG="C" ;
IFS=$(echo -e "\n\b") ;
nnumberOFinterface="0" ;

		if [ ! $EUID = 0 ] && [[ "$(ps aux | grep -v grep | grep -v nano | grep -v geany| grep shi3lD | awk '{print $2}' | wc -l) " -ge "1" ]] ;
	then
		echo -e " USAGE: sudo shi3lD \r depends on redundanz" ;
		exit 0 ;
else

# temp folder
		if [[ "$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" != '' ]] ; 
	then
		tmpfolder="$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" ;
	else
		tmpfolder="/tmp" ;
fi
# temp folder END

stop_Ppp(){
		echo -e "\nstopping connections ...\n" ;
		killall -15 dhclient ;
		sudo ip link set dev "$(cat "$tmpfolder"/interface)" down && wait && sleep 1 ;
}

# ASK
  case "$1" in
        --stop)
      shift 1;
      stop_Ppp "$@" ;
      ;;
  esac
fi
