#!/bin/bash
# mindevenviro stop_shield
###     WARNING:    DON'T EDIT ANYTHING BELOW       ###
LANG="C" ;
IFS=$(echo -e "\n\b") ;

		if [ ! $EUID = 0 ] ;
	then
		echo -e " USAGE: sudo shi3lD \r depends on redundanz" ;
		exit 0 ;
else

# temp folder
		if [[ "$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" != '' ]] ; 
	then
		tmpfolder="$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" ;
	else
		tmpfolder="/tmp" ;
fi
# temp folder END

stop_network(){
	sudo ip link set dev "$(cat "$tmpfolder"/interface)" down ; sleep 1 ;
}

main_(){
	stop_network ;
}
		if [[ "$(ps aux | grep -v grep | grep -v nano | grep shi3lD | awk '{print $2}' | wc -l) " -ge "1" ]] ;
	then
		main_ ;
fi
fi
