#!/bin/bash
# mindevenviro iptables rules redsocks
#
	if [[ "$(ps aux | grep -v grep | grep -v nano | grep -v geany | grep shi3lD | awk '{print $2}' | wc -l) " -ge "1" ]] && [ $EUID = 0 ] ;
then

iptables -t nat -A REDSOCKS -d 0.0.0.0/8 -j RETURN
iptables -t nat -A REDSOCKS -d 10.0.0.0/8 -j RETURN
iptables -t nat -A REDSOCKS -d 100.64.0.0/10 -j RETURN
iptables -t nat -A REDSOCKS -d 127.0.0.0/8 -j RETURN
iptables -t nat -A REDSOCKS -d 169.254.0.0/16 -j RETURN
iptables -t nat -A REDSOCKS -d 172.16.0.0/12 -j RETURN
iptables -t nat -A REDSOCKS -d 192.168.0.0/16 -j RETURN
iptables -t nat -A REDSOCKS -d 198.18.0.0/15 -j RETURN
iptables -t nat -A REDSOCKS -d 224.0.0.0/4 -j RETURN
iptables -t nat -A REDSOCKS -d 240.0.0.0/4 -j RETURN
iptables -t nat -A OUTPUT -p tcp -m owner --uid-owner $SUDO_USER -j REDSOCKS

else
	exit 0 ;
fi
