#!/bin/bash
# mindevenviro Transparently anonymizing traffic through TOR for a specific user with iptables
###     WARNING:    DON'T EDIT ANYTHING BELOW       ###   

		if [[ $EUID != 0 ]] || [[ ! "$(ps ax | grep -v grep | grep -v nano | grep -v geany| grep shi3lD | cut -f1 -d\ | wc -l) " -ge "1" ]] ;
	then
		echo -e " USAGE: sudo shi3lD" ;
		exit 0 ;
else

iptables -A OUTPUT -m conntrack --ctstate INVALID -j DROP
iptables -A OUTPUT -m state --state INVALID -j LOG --log-prefix "Transproxy state leak blocked: " --log-uid
iptables -A OUTPUT -m state --state INVALID -j DROP

iptables -A OUTPUT ! -o lo ! -d 127.0.0.1 ! -s 127.0.0.1 -p tcp -m tcp --tcp-flags ACK,FIN ACK,FIN -j LOG --log-prefix "Transproxy leak blocked: " --log-uid
iptables -A OUTPUT ! -o lo ! -d 127.0.0.1 ! -s 127.0.0.1 -p tcp -m tcp --tcp-flags ACK,RST ACK,RST -j LOG --log-prefix "Transproxy leak blocked: " --log-uid
iptables -A OUTPUT ! -o lo ! -d 127.0.0.1 ! -s 127.0.0.1 -p tcp -m tcp --tcp-flags ACK,FIN ACK,FIN -j DROP
iptables -A OUTPUT ! -o lo ! -d 127.0.0.1 ! -s 127.0.0.1 -p tcp -m tcp --tcp-flags ACK,RST ACK,RST -j DROP

iptables -t nat -A OUTPUT -p tcp -m owner --uid-owner $SUDO_USER -m tcp -j REDIRECT --to-ports 9040
iptables -t nat -A OUTPUT -p udp -m owner --uid-owner $SUDO_USER -m udp --dport 53 -j REDIRECT --to-ports 53
iptables -t filter -A OUTPUT -p tcp -m owner --uid-owner $SUDO_USER -m tcp --dport 9040 -j ACCEPT
iptables -t filter -A OUTPUT -p udp -m owner --uid-owner $SUDO_USER -m udp --dport 53 -j ACCEPT
iptables -t filter -A OUTPUT -m owner --uid-owner $SUDO_USER -j DROP

iptables -t nat -A OUTPUT -p tcp --dport 80 -m owner --uid-owner www-data -j DNAT --to-destination 127.0.1.1:80

fi
