#!/bin/bash
# mindevenviro wecker
# does beep if you should get up

LANG="C" ;
readonly empty='' ;

		if [[ ! $EUID =~ 1[0-9][0-9][0-9] ]] ;
	then
		echo "USAGE: dwecker" ;
		exit 0 ;
	else
	
beep(){
		while true
	do
		clear ;
		figlet wakeUp ;
		echo -e \\07 ;
		sleep .2 ;
	done
}
		exec 3>&1;
		result=$(dialog --inputbox minutes 0 0 2>&1 1>&3);

		if [[ "$result" = "$empty" ]] ;
	then
		exit 0 ;
	else
		let seconds="$result"*60
		exitcode=$?;
		exec 3>&-;
		clear ;
		
		while true
	do
		for i in $(seq 0 1 100) ;
	do
		if [[ "$seconds" != "0" ]] ;
	then
		((seconds--)) ;
		sleep 1 ;
		figlet $seconds
	else
		beep ;
fi
	done
done
fi
fi
