#!/bin/bash
# mindevenviro wecker
# does beep if you should get up
LANG="C" ;
readonly empty='' ;

		if [[ ! $EUID =~ 1[0-9][0-9][0-9] ]] ;
	then
		echo "USAGE: dwecker" ;
		exit 0 ;
	else
	
beep(){
		figlet wakeup! ;
		cvlc -R $HOME/.config/wakeup.mp3 2>/dev/null ;
}
		exec 3>&1;
		result=$(dialog --inputbox minutes 0 0 2>&1 1>&3);
	
		if [[ "$result" = "$empty" ]] ;
	then
		exit 0 ;
	else
		let seconds="$result"*60
		exitcode=$? ;
		exec 3>&- ;

		while true
	do
		if [[ "$seconds" != "0" ]] ;
	then
		((seconds--));
		sleep 1 && figlet $seconds;
		clear;
	else
		clear ;
		beep ;
fi
done
fi
fi
