#!/bin/bash
# changes the background in vtwm, with pictures from folder Pictures
# . I will update some pictures
LANG="C" ;
IFS=$(echo -en "\b\n") ;
find $HOME/Pictures/. -type f | grep -E 'jpg|png|gif|xpm|tiff|JPG|PNG|jpeg|JPEG' | sed 's/\ /\\ /g' | sort -R | head -n1 | xargs feh --bg-scale ;
