#!/bin/bash
# mindevenviro hi
# startup file on /usr/local/bin
###     WARNING:    DON'T EDIT ANYTHING BELOW       ###
LANG="C" ;
to_star_up(){
xsetroot -solid yellow &
sleep 3 ;
oclock -hour red -minute white -bd white -bg black -jewel green -shape -geometry 70x75-6+3 &
xload -g 60x58-10+91 -fg "grey" -bg "black" -bw 1 &
setsid xscreensaver -display :0 -no-splash >/dev/null 2>&1 < /dev/null &
xcompmgr -c &
sleep 1 ;
terminator &
sleep 1 ;
feh-bg &
sleep 1 ;
transset --name "mind eve n viro" .8 ;
}
		if [[ $(ps axu | grep -v grep | grep terminator) = '' ]] && \
		[[ $(ps axu | grep -v grep | grep xload) != '' ]] && \
		[[ $(ps axu | grep -v grep | grep xscreensaver) != '' ]] ;
	then
		terminator &
		sleep 3;
		transset --name "mind eve n viro" .8 && wait && exit 0 ;

		elif [[ $(ps axu | grep -v grep | grep oclock) = '' ]] || \
		[[ $(ps axu | grep -v grep | grep xload) = '' ]] || \
		[[ $(ps axu | grep -v grep | grep xscreensaver) = '' ]] ;
	then
		to_star_up && wait && exit 0 ;
	else
		exit 0 ;
fi
