#!/bin/bash
# startup file in /usr/local/bin for .twmrc
# Schach
LANG="C" && hi &
                if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_brutalchess | grep brutalchess) = '' ]] ;
        then
                brutalchess &
                exit 0 ;
        else
                exit 0 ;
fi

