#!/bin/bash
# startup file on /usr/local/bin
# Schach
LANG="C" && hi ;
                if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_brutalchess | grep brutalchess) = '' ]] ;
        then
                brutalchess &
                exit 0 ;
        else
                exit 0 ;
fi

