#!/bin/bash
# startup file on /usr/local/bin

LANG="C" && hi ;
IFS=$(echo -en "\b\n") ;

			if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_dwecker | grep dwecker) = '' ]] ;
        then
                xterm -title dwecker -fg green -geometry 35x20+20-20 -e dwecker &
                transset --name "dwecker" .7 ;
                exit 0 ;
        else
                exit 0 ;
fi
