#!/bin/bash
# startup file on /usr/local/bin
LANG="C" && hi ;

		if [[ ! $(netstat -ar) =~ 'default' ]] ;
	then
		exit 0 ;
else
                if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_firefox-esr | grep firefox-esr) = '' ]] ;
        then
                firefox-esr &
                exit 0 ;
        else
                exit 0 ;
fi
fi
