#!/bin/bash
# startup file in /usr/local/bin for .twmrc
LANG="C" && hi &  
IFS=$(echo -en "\b\n") ;

		if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_gimp | grep gimp) = '' ]] ;
        then
                gimp &
                exit 0 ;
        else
                exit 0 ;
fi
