#!/bin/bash
# startup file on /usr/local/bin
LANG="C"; 
                if [[ $(ps axu | grep -v grep | grep -v nano | grep -v hi_geany | grep geany) = '' ]] ;
        then
                geany &
                hi && exit 0 ;
        else
                hi && exit 0 ;
fi

