#!/bin/bash
# startup file in /usr/local/bin for .twmrc
LANG="C" && hi &  
                if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_libreoffice | grep libreoffice) = '' ]] ;
        then
                libreoffice &
                exit 0 ;
        else
                exit 0 ;
fi

