#!/bin/bash
# startup file on /usr/local/bin
LANG="C" ;
                if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_playonlinux | grep playonlinux) = '' ]] ;
        then
                playonlinux & hi ;
                exit 0 ;
        else
                exit 0 ;
fi

