#!/bin/bash
# startup file in /usr/local/bin for .twmrc
LANG="C" && hi &  

                if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_playonlinux | grep playonlinux) = '' ]] ;
        then
                playonlinux &
                exit 0 ;
        else
                exit 0 ;
fi
