#!/bin/bash
# startup file on /usr/local/bin
# mindevenviro pidgin   
LANG="C" && hi ;
IFS=$(echo -en "\b\n") ;

		if [[ ! "$(ps aux | grep -v grep | grep -v nano | grep -v geany| grep firefox-esr | awk '{print $2}' | wc -l) " -ge "1" ]] && [[ ! $(netstat -ar) =~ 'default' ]] ;
	then
		exit 0 ;
else
		if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_pidgin | grep pidgin) = '' ]] ;
	then
		pidgin 2>/dev/null &
		sleep 1 ;
		transset --name "Buddy List" .7 ;
		exit 0 ;
	else
		exit 0 ;
fi
fi
