#!/bin/bash
# startup file on /usr/local/bin
LANG="C" && hi ;

		if [[ ! "$(ps aux | grep -v grep | grep -v nano | grep -v geany| grep shi3lD | awk '{print $2}' | wc -l) " -ge "1" ]] && [[ ! $(netstat -ar) =~ 'default' ]] ;
	then
		exit 0 ;
else
                if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_playonlinux | grep playonlinux) = '' ]] ;
        then
                playonlinux &
                exit 0 ;
        else
                exit 0 ;
fi
fi

