#!/bin/bash
# startup file on /usr/local/bin
# mindevenviro pidgin   
LANG="C" && hi ;
IFS=$(echo -en "\b\n") ;

		if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_pidgin | grep pidgin) = '' ]] ;
	then
		pidgin 2>/dev/null &
		exit 0 ;
	else
		exit 0 ;
fi
