#!/bin/bash
# startup file on /usr/local/bin   
# shi3lD
# redundanz   
LANG="C" && hi ;
	                if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_shi3lD | grep shi3lD) = '' ]] ;
        then
				if [ $EUID != 0 ] ;
		then
				gksudo -g "$0" ;
		else
                xterm -title shi3lD -bw 0 -geometry 80x15+20-20 -e shi3lD &
                sleep 1 ;
                transset --name shi3lD .7 ;

	                if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_shi3lD | grep redundanz) = '' ]] ;
        then
				xterm -title redundanz -bw 0 -geometry 110x15+507-20 -e redundanz --monitor &
				sleep 1 ;
				transset --name redundanz .7
				hi_wicd-client ;
                exit 0 ;
        else
				exit 0 ;
		fi
fi
		else
				exit 0 ;
fi
