#!/bin/bash
# startup file on /usr/local/bin   
# shi3lD
LANG="C" ;
                if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_shi3lD | grep shi3lD) = '' ]] ;
        then
                xterm -title shi3lD -bw 0 -geometry 100x15+20-20 -e gksudo -u root shi3lD & hi_wicd-client ;
                exit 0 ;
        else
                exit 0 ;
fi
