#!/bin/bash
# startup file on /usr/local/bin
LANG="C" && hi ;
                if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_transmission-gtk | grep transmission-gtk) = '' ]] ;
        then
                transmission-gtk &
                exit 0 ;
        else
                exit 0 ;
fi

