#!/bin/bash
# startup file on /usr/local/bin
LANG="C" && hi ;

		if [[ ! "$(ps aux | grep -v grep | grep -v nano | grep -v geany| grep firefox-esr | awk '{print $2}' | wc -l) " -ge "1" ]] ;
	then
		exit 0 ;
else
                if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_transmission-gtk | grep transmission-gtk) = '' ]] ;
        then
                transmission-gtk &
                exit 0 ;
        else
                exit 0 ;
fi
fi
