#!/bin/bash
# startup file in /usr/local/bin for .twmrc
LANG="C" && hi &  
IFS=$(echo -en "\b\n") ;

		if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_vlc | grep vlc) = '' ]] ;
	then
		vlc -I skins2 --skins2-last=/usr/share/vlc/skins2/MyVLCtheme.vlt --no-fullscreen --no-video-title-show --no-autoscale --global-key-zoom-quarter 1:4 vlc --playlist-autostart Music/myMusic.m3u 2>/dev/null &
		exit 0 ; 
	else
		exit 0 ;
fi
