#!/bin/bash
# startup file on /usr/local/bin
LANG="C" ;
IFS=$(echo -en "\b\n") ;

		if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_vlc | grep vlc) = '' ]] ;
	then
		vlc --no-fullscreen --no-video-title-show --no-autoscale --global-key-zoom-quarter 1:4 & hi ;
		exit 0 ;
	else
		exit 0 ;
fi
