#!/bin/bash
# startup file on /usr/local/bin
LANG="C" && hi &  
IFS=$(echo -en "\b\n") ;

		if [[ ! $(netstat -ar) =~ 'default' ]] ;
	then
		xmessage -center -buttons Ok:0 -default Ok -nearmouse "open first "shi3lD" from the menu" -timeout 7 &
		exit 0 ; 
else
		if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_vlc | grep vlc) = '' ]] ;
	then
		vlc -I skins2 --skins2-last=/usr/share/vlc/skins2/MyVLCtheme.vlt --no-fullscreen --no-video-title-show --no-autoscale --global-key-zoom-quarter 1:4 &
		exit 0 ; 
	else
		exit 0 ;
fi
fi
