#!/bin/bash
# startup file on /usr/local/bin
# mindevenviro wireshark   
LANG="C"; 
IFS=$(echo -en "\b\n") ;

		if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_wireshark | grep wireshark) = '' ]] ;
	then
		wireshark 2>/dev/null &
		hi && exit 0 ; 
	else
		hi && exit 0 ; 
fi
