#!/bin/bash
# startup file on /usr/local/bin
LANG="C" && hi ;
                if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_wicd-client | grep wicd-client) = '' ]] ;
        then
			if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_wicd-client | grep shi3lD) = '' ]] ;
		then
				wicd-client -n &
	fi
        else
				exit 0 ;
fi

