#!/bin/bash
# startup file on /usr/local/bin
# mindevenviro wireshark   
LANG="C" && hi; 
IFS=$(echo -en "\b\n") ;

		if [[ ! $(netstat -ar) =~ 'default' ]] ;
	then
		xmessage -center -buttons Ok:0 -default Ok -nearmouse "no Internet, connect with sh13lD" -timeout 7 &
		exit 0; 
else
		if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_wireshark | grep wireshark) = '' ]] ;
	then
		wireshark 2>/dev/null &
		exit 0; 
	else
		exit 0; 
fi
fi
