#!/bin/bash
# startup file on /usr/local/bin
# xcalc
LANG="C"; 
IFS=$(echo -en "\b\n") ;

			if [[ $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep -v hi_xcalc | grep xcalc) = '' ]] ;
        then
                xcalc &
                hi && exit 0 ;
        else
                hi && exit 0 ;
fi
