#!/bin/bash
# mindevenviro codecounter
# sets the actual lines, words and chars from all shell scripts in /home/$SUDO_USER/mindevenviro
# without blank lines and without comments
###     WARNING:    DON'T EDIT ANYTHING BELOW       ###
LANG="C" ;

	if [ $EUID = 0 ] && [[ "$(ps aux | grep -v grep | grep -v geany | grep -v nano | grep sCRYPtUPdater | awk '{print $2}' | wc -l) " -ge "1" ]] && [[ $(cat /home/ivo/mindevenviro/.git/logs/refs/remotes/origin/master | grep push) != '' ]] ;
then
	# CodeCounter
	for i in $(find /home/$SUDO_USER/mindevenviro -type f | grep -vE '.git' | grep -vE 'pics|thirdparty|.js|.sqlite'); 
do 
	foreach=$(cat "$i" | grep -vE '#' | tr -d '\b' | sed -e '/^\s*$/d' | wc -l) &&
	let lines="$lines"+"$foreach" &&
	sed -i "s/\(\Lines = *\).*/\1$lines/" /home/$SUDO_USER/mindevenviro/docs/README.md && wait ;
	foreach1=$(cat "$i" | grep -vE '#' | tr -d '\b' | sed -e '/^\s*$/d' | wc -w) &&
	let words="$words"+"$foreach1" &&
	sed -i "s/\(\Words = *\).*/\1$words/" /home/$SUDO_USER/mindevenviro/docs/README.md && wait ;
	foreach2=$(cat "$i" | grep -vE '#' | tr -d '\b' | sed -e '/^\s*$/d' | wc -c) &&
	let chars="$chars"+"$foreach2" &&
	sed -i "s/\(\Chars = *\).*/\1$chars/" /home/$SUDO_USER/mindevenviro/docs/README.md && wait ;
done
echo -e "codecounter $(date) :: as $SUDO_USER :: in $(uname -n) :: changed: $lines Lines, $words Words, $chars Chars, in README.md" >> "/home/$SUDO_USER/.wH0rUNSon" ;
sleep 1
exit 0 ;
else
echo -e " ... this script updates the lines, words and chars of\n ... executable code in the mindevenviro folder\n ... you must contribute to mindevenviro\r" ;
exit 0 ;
fi
