#!/bin/bash
# mindevenviro connected
# lists outgoing TCP and UDP and update to stdout by hitting enter

		if [[ "$EUID" =~ 1[0-9][0-9][0-9] ]] ;
	then
		while true
	do
		clear ;
		echo -e "\nupdating ..." ;
		sleep 1;
		netstat -an | grep -v LISTENING | grep -E "LISTEN|ESTABLISHED" ;
		read -r ;
done
else
	exit 0 ;
fi
