#!/bin/bash
# mindevenviro connected 
# lists outgoing TCP and UDP and update to stdout by hitting enter
###     WARNING:    DON'T EDIT ANYTHING BELOW       ###
		if [[ "$EUID" != 0 ]] ;
	then
		sudo "$0" ;
	else
		while true
	do
		clear ;
		echo -e "\nupdating ..." ;
		sleep 1;
		netstat -ap4n | grep -v LISTENING | grep -E "LISTEN|ESTABLISHED" | uniq -cui ;
		read -r ;
done
fi
