#!/bin/bash
# mindevenviro logdiskussage
# shows big log files in Megabytes and monitors by hitting enter
LANG="C";
		if [[ "$EUID" != 0 ]] ;
	then
		sudo "$0"
	else
		while true
	do
		clear ;
		echo -e "\nupdating ..." ;
		sleep 1;
		du -h /var/log/*log* | grep -E "M" ;
		read -r ;
done
fi
