#!/bin/bash
# mindevenviro set_mysql_passwd
# sets the root password for mariadb
###     WARNING:    DON'T EDIT ANYTHING BELOW       ###
#
LANG=C ;
#
		if [ $EUID != 0 ] ;
	then
		echo "please sudo"
		exit 0 ;
	else
		mysqlconn="mysql -u root";
help(){
shift 0 ;
echo -e "hello $SUDO_USER\nset new mariadb root password\n" ;
echo -e "Usage: $0 [--password] [password_value]\r";
exit 0 ;
}		

stopmysql(){

		/etc/init.d/mysql stop && wait ;

		killall -15 serv-if-up 2>/dev/null && wait ;
		
		for tokill in $(ps aux | grep -v grep | grep -v set_mysql_passwd | grep mysql | awk '{print $2}') ;
	do
		kill -15 "$tokill" 2>/dev/null ;
	done;
		for tokill3 in $(ps aux | grep -v grep | grep -v set_mysql_passwd | grep mysqld_safe | awk '{print $2}') ;
	do
		kill -15 "$tokill3" 2>/dev/null ;
	done;
		for tokill4r in $(ps aux | grep -v grep | grep -v set_mysql_passwd | grep serv-if-up | awk '{print $2}') ;
	do
		kill -15 "$tokill4r" 2>/dev/null ;
	done;
	}

changepass(){

		if	[[ "$mysqlnewpass" != '' ]] ;
	then
		stopmysql ;
		
		echo -e "\nstarting mysqld_safe to maintenance, please wait...\n" ;
		
		sudo mysqld_safe --skip-grant-tables 2> /dev/null &
		
		sleep 15 ;

		echo -e "\nGoing to change the password\n" ;

		$mysqlconn -e "use mysql; update mysql.user set password=password('$mysqlnewpass') where user='root';" && sleep 3;
		$mysqlconn -e "use mysql; FLUSH PRIVILEGES;" && sleep 3 ;
		
		sleep 3 ;
		
		killall -15 mysqld_safe && wait && sleep 3 ; 
		
		echo -e "\nupdating mysql root passwords...\n" ;
		sed -i "s/\(p4SSWORD *= *\).*/\1$mysqlnewpass/" /etc/mysql_cp_db_password.conf;
		
		echo -e "\nrestarting mysql...\n";
		/etc/init.d/mysql start && wait ;

		echo -e "\nrestarting serv-if-up...\n";
		setsid serv-if-up 2>/dev/null 2>&1 < /dev/null &

		sleep 3;

		echo -e "\ndone!\n";
		exit 0;
	else
		echo "you must enter a password";
		echo "USAGE: $0 --help";
		exit 1;
fi
}

# ASK 
  case "$1" in
   --password)
		REPLY="set"
		mysqlnewpass=$2
        toshiffta=$(echo "$1 $mysqlnewpass" | wc -w) ;
        shift "$toshiffta" ;
      ;;
   --help)
		REPLY="help"
		shift
		help ;
      ;; 
  esac

		if [[ "$REPLY" = "set" ]] ;
	then
		changepass "$@" ;
		
		elif [[ "$REPLY" = "help" ]] ;
	then
		help ;
	else
		echo "Try 'sudo $0 --help' for more information."
		exit 0 ;
	fi
fi
