#!/bin/bash
# mindevenviro set_mysql_passwd
# sets the root password for mariadb
###     WARNING:    DON'T EDIT ANYTHING BELOW       ###
#
LANG=C ;
#
		if [ $EUID != 0 ] ;
	then
		echo "please sudo"
		exit 0 ;
	else
		mysqlconn="sudo mysql -u root";
help(){
shift 0 ;
echo -e "hello $SUDO_USER\nset new mariadb root password\n" ;
echo -e "Usage: $0 [--password] [password_value]\r";
exit 0 ;
}		

stopmysql(){
		killall -15 serv-if-up 2>/dev/null ;
		
		for tokill in $(ps aux | grep -v grep | grep -v set_mysql_passwd | grep mysql | awk '{print $2}') ;
	do
		kill -9 "$tokill" 2>/dev/null ;
	done;
		for tokill in $(ps aux | grep -v grep | grep -v set_mysql_passwd | grep mysqld_safe | awk '{print $2}') ;
	do
		kill -9 "$tokill" 2>/dev/null ;
	done;
	}

changepass(){
		if	[[ "$mysqlnewpass" != '' ]] ;
	then
		stopmysql ;
		echo "starting mysql to maintenance" ;
		mysqld_safe --skip-grant-tables &
		sleep 3 ;
		$mysqlconn -e "use mysql; update mysql.user set password=password('$mysqlnewpass') where user='root';"
		$mysqlconn -e "use mysql; FLUSH PRIVILEGES;"
		killall -9 mysqld_safe && wait ; 
		echo "... update mysql root passwords" ;
		sed -i "s/\(p4SSWORD *= *\).*/\1$mysqlnewpass/" /etc/mysql_cp_db_password.conf;
		echo "starting mysql and serv-if-up";
		/etc/init.d/mysql start;
		nice -14 setsid serv-if-up >/dev/null 2> /dev/null &
		echo "done!";
		exit 0;
	else
		echo "you must enter a password";
		echo "USAGE: $0 --help";
		exit 0;
fi
}

# ASK 
  case "$1" in
   --password)
		REPLY="set"
		mysqlnewpass=$2
        toshiffta=$(echo "$1 $mysqlnewpass" | wc -w) ;
        shift "$toshiffta" ;
      ;;
   --help)
		REPLY="help"
		shift
		help ;
      ;; 
  esac

		if [[ "$REPLY" = "set" ]] ;
	then
		changepass "$@" ;
		
		elif [[ "$REPLY" = "help" ]] ;
	then
		help ;
	else
		echo "Try 'sudo $0 --help' for more information."
		exit 0 ;
	fi
fi
