#!/bin/bash
# mindevenviro-windows search
# I use dos2unix to convert file endings
###	WARNING: DON'T EDIT ANYTHING BELOW ###
#set -x
LANG="C" ;
IFS="$(echo -en "\n\b")" ;
line='' ;
pause="1" ;
			if [[ "$EUID" != "0" ]] ;
		then
	echo -e "sudo search -h :: please\n" ;
	help_function ;
else

help_function(){
echo -e "\nUsage: sudo search [-s|--search] [PATH] [TOSEARCH] [TOGREP] [TOEXCLUDE]\n
SEARCH THE DRIVE\n
 This script searches your drive\r
 for everything in it, and displays on the Terminal.\r
 Finds: log files, example code, .conf to edit...\n
 [PATH]: the absolute path like: /var/
 [TOSEARCH]: search pattern\r
 [TOGREP]: search a word in file\r
 [TOEXCLUDE]: a word you want to exclude from your search results.\n" ;
exit 0 ;
}

searchStat(){
#echo "searchStat function"
	echo -e "search $(date) :: as $SUDO_USER :: in $(uname -n) :: search in $searchP4th grep:"$togrep" exclude:"$exclud3" ::" >>"/home/$SUDO_USER/.wH0rUNSon" && wait ;
}

#exithandler
exitHandl3R(){
#echo "exitHandl3R function"
	searchStat;
	pgrep less | awk "{print $1}" | xargs kill -15 2>/dev/null ; 
	pgrep nano | awk "{print $1}" | xargs kill -15 2>/dev/null ; 
	pgrep mupdf | awk "{print $1}" | xargs kill -15 2>/dev/null ;
	echo -e "\n ... good bye $SUDO_USER" ;
	exit 0 ;
}

# displayer
displayer(){
			while read line
		do
			if [[ "$line" != '' ]] && [[ ! $(echo "$line" | xargs file | cut -f2 -d:) =~ '(no magic)'|'empty' ]] ;
		then
			# uS3F is the owner of the file
			uS3F=$(ls -sl "$line" | awk '{print $4}' | tr -d '\ ');
###
				if [[ $(echo "$line" | xargs basename | sed 's/\./\ /g' | awk '{print $2}') =~ 'conf'|'ini'|'config'|'h'|'py' ]] \
				&& [[ ! $(echo "$line" | xargs file) =~ 'shared '|'dynamically '|'interpreter '|'ELF ' ]]; # to not open binaries
			then
				pause="1" ;
				opener="nano";
				return ;

				# count with dd magic number 20 to determine the file type to be editet and not to open binaries
				elif [[ $(dd if="$line" bs=20 count=1 | tr '\0' '\n') =~ 'bash'|'perl'|'php'|'python'|'sh' ]] \
				&& [[ ! $(echo "$line" | xargs file) =~ 'shared '|'dynamically '|'interpreter '|'ELF ' ]];
			then
				pause="1" ;
				opener="nano";
				return ;

				elif [[ ! $(echo "$line" | xargs basename | sed 's/\./\ /g' | awk '{print $2}') =~ 'conf'|'ini'|'config' ]] \
				|| [[ ! $(echo "$line" | xargs file) =~ 'shared '|'dynamically '|'interpreter '|'ELF ' ]] ;
			then
				pause="1" ;
				opener="less";
				return ;
		
				elif [[ $(dpkg -l | grep mupdf | awk '{print $2}') != '' ]] && [[ $(echo "$line" | xargs file) =~ PDF ]] ;
			then
				pause="1" ;
				opener="mupdf";
				return ;

				elif [[ ! $(echo "$line" | xargs file) =~ PDF|PHP|script|ASCII|text|TEXT|HTML|XML ]] \
				|| [[ $(echo "$line" | xargs file) =~ 'shared '|'dynamically '|'interpreter '|'ELF ' ]];
			then
				pause="0" ;
				echo -e " ... no PDF|PHP|script|ASCII|text|TEXT|HTML|XML \r" 
				echo -e " ... nothing to show ::\n" ;
				return ;
		fi
fi
done<<<""$line"";
}
#displayer END

goFurther(){
				sleep 1 ;
				echo "-" ;
				printf " ...enter to continue: " ; read -r ;
				echo "-" ;
				displayer ;
}

# Main function
main(){
#echo "main function"
searchP4th="$2";
searchP4ttern="$3";
togrep="$4";
exclud3="$5";
					trap 'exitHandl3R' SIGINT ;
###
			if  [[ "$exclud3" != '' ]] || [[ "$togrep" != '' ]] ;
		then
				for line in $(find $searchP4th -name *$searchP4ttern* -type f ) ;
			do
				displayer;
###				
			if [ $pause = 1 ] ;
		then
				if [[ "$exclud3" != '' ]] && [[ "$togrep" != '' ]] ;
			then
				echo "$line" | xargs cat | grep -E "$togrep" | grep -vE "$exclud3" ;
				exitc0de=$(echo $?) ;
			fi
				if [[ "$exclud3" = '' ]] && [[ "$togrep" != '' ]] ;
			then
				echo "$line" | xargs cat | grep -E "$togrep" | grep -vE "$exclud3" ;
				exitc0de=$(echo $?) ;
			fi
				if [[ $exitc0de = 0 ]] ;
			then
				if [[ "$opener" = "nano" ]]; 
			then
				printf " ...do you want to edit, Y/N " ; read -r ;

			if [[ $REPLY =~ Y|y|ok|j|J ]] ;	###
		then
				sudo -u "$uS3F" "$opener" "$line" ;
				goFurther ;
		fi
	fi
fi
			if [[ "$opener" =~ less|mupdf ]];
		then
				if [[ "$exclud3" != '' ]] && [[ "$togrep" != '' ]] ;
			then
				echo "$line" | xargs cat | grep -E "$togrep" | grep -vE "$exclud3" ;
				exitc0de=$(echo $?) ;
			fi
				if [[ "$exclud3" = '' ]] && [[ "$togrep" != '' ]] ;
			then
				echo "$line" | xargs cat | grep -E "$togrep" | grep -vE "$exclud3" ;
				exitc0de=$(echo $?) ;
			fi
				if [[ $exitc0de = 0 ]] ;
			then
				sudo -u "$uS3F" "$opener" "$line" ;
				goFurther;
				fi
			fi
fi
###
		if [ $pause = 0 ] ;
	then
		goFurther;
	fi
done
	else
			help_function ;
fi
###
}

# ASK
  case "$1" in
		-s|--search)
        toshiffta=0 ;
        shift "$toshiffta" ;		
		main "$@" ;
        ;;
        -h|--help)
        toshiffta=0 ;
        shift "$toshiffta" ;
		help_function "$@" ;
        ;;
esac
# ASK END
fi
