#!/bin/bash
# mindevenviro logout vtwm
###     WARNING:    DON'T EDIT ANYTHING BELOW       ###
LANG="C" ;
readonly empty='';
		if [[ "$EUID" != "0" ]] || [[ "$(ps ax | grep -v grep | grep -v nano | grep -v geany| grep xdm | cut -f2 -d\ ) " = "$empty" ]] ;
	then
		echo -e " ... use \"exit\" from the \"VTWM-Menu\" or press F1 on your keyboard to log out." ;
		exit 0;
else

# temp folder
		if [[ "$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" != '' ]] ; 
	then
		tmpfolder="$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" ;
	else
		tmpfolder="/tmp" ;
fi
# temp folder END

interface="$(cat "$tmpfolder"/interface)" ;

# which interface is trought the default route to the internet connected
# works only if you have two interfaces, like: eno[0-9] | eth[0-9] | wi[a-z-0-9] | wl[a-z-0-9]

		if [[ "$interface" =~ eno|eth ]] ;
	then
		whoUP="1" ;

		elif [[ "$interface" =~ wl|wi ]] ;
	then
		whoUP="2" ;
	else
		whoUP="none" ;
fi

# primary monitor
primM0n=$(xrandr | sed -n '/'\ connected\ '/p' | grep -E '\ primary\ ' | awk '{print $1}') ;
# primarys monitor Aufloesung
aufloeprim=$(xrandr | grep -E '\ connected\ ' | sed -n 's/primary//p' | awk '{print $3}' | cut -f1 -d+) ; 
# secondarys monitor
sec0dM0n=$(xrandr | sed -n '/'\ connected\ '/p' | grep -vE '\ primary\ ' | awk '{print $1}') ;
# set to primary monitor
xrandr --output "$sec0dM0n" --off && xrandr --output "$primM0n" --mode "$aufloeprim" ;
# stop network
stop_shield --stop &
# revert vendors MAC
sudo ip link set dev "$interface" address "$(cat /root/.vendorsmac | head -n"${whoUP}" | tail -n1)" ;
# kill zombie wine processes
	for killwines in $(ps axu | grep -v grep | grep -v nano | grep -v geany | grep playonlinux | awk '{print $2}' | sort -r);
do
	echo $killwines | xargs kill -15 && wait ;
done
# kill nice
killall -15 serv-if-up 2>/dev/null && wait ;
sleep 1 ;
killall -15 xterm && wait ;
sleep 1 ;
killall -15 cheese && wait ;
sleep 1 ;
killall -15 vlc && wait ;
sleep 1 ;
killall -15 terminator && wait ;
sleep 1 ;
rm -f $tmpfolder/* ;
exit 0 ;
#
fi
