# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * 
 * Adapted for mindevenviro, all plugins where installed with apt-get from a
 * debian archive, March 2018 github.com/doivglser
 * 
 */

user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.ctrlTab.previews", false);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "~/Downloads");
user_pref("browser.download.panel.shown", true);
user_pref("browser.migrated-sync-button", true);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.update", false);
user_pref("browser.tabs.remote.autostart.2", false);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.e10s.rollout.hasAddon", true);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.https_everywhere._observatory.alt_roots", true);
user_pref("extensions.https_everywhere._observatory.enabled", true);
user_pref("extensions.https_everywhere.firstrun_context_menu", false);
user_pref("extensions.https_everywhere.toolbar_hint_shown", true);
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.update.autoUpdateDefault", false);
user_pref("lightweightThemes.persisted.footerURL", false);
user_pref("lightweightThemes.persisted.headerURL", false);
user_pref("media.gmp-gmpopenh264.enabled", true);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.prefetch-next", false);
user_pref("noscript.global", true);
user_pref("noscript.visibleUIChecked", true);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("pref.browser.homepage.disable_button.restore_default", true);
user_pref("pref.general.disable_button.default_browser", true);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("services.sync.migrated", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.myFiltersPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.myRulesPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.tpFiltersPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.whitelistPane", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
