# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1522759591);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1522759560);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 42);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1522759611186");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1522761294186");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1522759565946");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1522763165946");
user_pref("browser.search.countryCode", "CH");
user_pref("browser.search.region", "CH");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180326230345");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1522759562");
user_pref("browser.slowStartup.averageTime", 3516);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage", "https://check.torproject.org/");
user_pref("browser.startup.homepage_override.buildID", "20180326230345");
user_pref("browser.startup.homepage_override.mstone", "52.7.3");
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"https-everywhere-button\",\"pocket-button\",\"ublock0-button\",\"noscript-tbb\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"pocket-button\",\"ublock0-button\",\"developer-button\"],\"dirtyAreaCache\":[\"addon-bar\",\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("capability.policy.maonoscript.sites", "about: about:addons about:blank about:blocked about:certerror about:config about:crashes about:feeds about:home about:memory about:neterror about:plugins about:preferences about:privatebrowsing about:sessionrestore about:srcdoc about:support blob: chrome: mediasource: moz-extension: moz-safe-about: resource:");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1522759622844");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 3836);
user_pref("datareporting.sessions.current.main", 41);
user_pref("datareporting.sessions.current.sessionRestored", 3569);
user_pref("datareporting.sessions.current.startTime", "1522759559286");
user_pref("datareporting.sessions.current.totalTime", 78);
user_pref("e10s.rollout.cohort", "disqualified-test");
user_pref("e10s.rollout.cohortSample", "0.413088");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"e10srollout@mozilla.org\":{\"version\":\"1.10\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox-esr/browser/features/e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"aushelper@mozilla.org\":{\"version\":\"2.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox-esr/browser/features/aushelper@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"webcompat@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox-esr/browser/features/webcompat@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"firefox@getpocket.com\":{\"version\":\"1.0.5\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox-esr/browser/features/firefox@getpocket.com.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"uBlock0@raymondhill.net\":{\"version\":\"1.10.4\",\"type\":\"extension\",\"descriptor\":\"/usr/share/xul-ext/ublock-origin\",\"multiprocessCompatible\":true,\"runInSafeMode\":false,\"dependencies\":[],\"hasEmbeddedWebExtension\":false}}");
user_pref("extensions.databaseSchema", 19);
user_pref("extensions.e10s.rollout.blocklist", "{dc572301-7619-498c-a57d-39143191b318};support@lastpass.com;");
user_pref("extensions.e10s.rollout.hasAddon", true);
user_pref("extensions.e10s.rollout.policy", "51set1");
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "%7B73a6fe31-595d-460b-a920-fcc0f8843232%7D:2.9.0.14,https-everywhere-eff%40eff.org:5.2.8,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:52.7.3");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.https_everywhere._observatory.clean_config", true);
user_pref("extensions.https_everywhere._observatory.enabled", true);
user_pref("extensions.https_everywhere._observatory.popup_shown", true);
user_pref("extensions.https_everywhere._observatory.use_custom_proxy", true);
user_pref("extensions.https_everywhere.firstrun_context_menu", false);
user_pref("extensions.https_everywhere.prefs_version", 1);
user_pref("extensions.https_everywhere.toolbar_hint_shown", true);
user_pref("extensions.lastAppVersion", "52.7.3");
user_pref("extensions.lastPlatformVersion", "52.7.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ublock0.cloudStorage.myFiltersPane", "");
user_pref("extensions.ublock0.cloudStorage.myRulesPane", "");
user_pref("extensions.ublock0.cloudStorage.tpFiltersPane", "");
user_pref("extensions.ublock0.cloudStorage.whitelistPane", "");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"e10srollout@mozilla.org\":{\"d\":\"/usr/lib/firefox-esr/browser/features/e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.10\",\"st\":1522105425000},\"aushelper@mozilla.org\":{\"d\":\"/usr/lib/firefox-esr/browser/features/aushelper@mozilla.org.xpi\",\"e\":true,\"v\":\"2.0\",\"st\":1522105425000},\"webcompat@mozilla.org\":{\"d\":\"/usr/lib/firefox-esr/browser/features/webcompat@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1522105425000},\"firefox@getpocket.com\":{\"d\":\"/usr/lib/firefox-esr/browser/features/firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.5\",\"st\":1522105425000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox-esr/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"52.7.3\",\"st\":1522105425000}},\"app-system-share\":{\"uBlock0@raymondhill.net\":{\"d\":\"/usr/share/xul-ext/ublock-origin\",\"e\":true,\"v\":\"1.10.4\",\"st\":1517584797000,\"mt\":1484022851000},\"{73a6fe31-595d-460b-a920-fcc0f8843232}\":{\"d\":\"/usr/share/xul-ext/noscript\",\"e\":true,\"v\":\"2.9.0.14\",\"st\":1522305650000,\"mt\":1470643768000},\"https-everywhere-eff@eff.org\":{\"d\":\"/usr/share/xul-ext/https-everywhere\",\"e\":true,\"v\":\"5.2.8\",\"st\":1522305646000,\"mt\":1385856000000}}}");
user_pref("media.gmp-manager.buildID", "20180326230345");
user_pref("media.gmp-manager.lastCheck", 1522759624);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("noscript.ABE.migration", 1);
user_pref("noscript.gtemp", "");
user_pref("noscript.subscription.lastCheck", -1953819742);
user_pref("noscript.temp", "");
user_pref("noscript.version", "2.9.0.14");
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 122334);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.myFiltersPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.myRulesPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.tpFiltersPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.whitelistPane", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1522759559);
user_pref("toolkit.telemetry.cachedClientID", "1501dd03-4446-4b9b-b269-7e5eeb95a9fc");
user_pref("toolkit.telemetry.previousBuildID", "20180326230345");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
