# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * 
 * Adapted for mindevenviro, all plugins where installed with apt-get from a
 * debian archive, March 2018 github.com/doivglser
 * 
 */

user_pref("browser.startup.homepage", "https://check.torproject.org/");
