#!/bin/bash
# mindevenviro start_shield
###     WARNING:    DON'T EDIT ANYTHING BELOW       ###

LANG="C";
IFS=$(echo -e "\n\b");

		if [[ "$EUID" != "0" ]] || [[ "$(ps ax | grep -v grep | grep -v nano | grep -v geany | grep mde-setup | cut -f2 -d\ ) " = '' ]] ;
	then
		echo "USAGE: sudo mde-setup, updates your /etc/hosts file." ;
		exit 0;
else
		# tmp folder
		if [[ "$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" != '' ]] ;
	then
		tmpfolder="$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" ;
	else
		tmpfolder="/tmp" ;
fi
# tmp folder END

	# update hosts and set the address for apache2 http server
	sed -e 's/x0x/'$(hostname)'/p' /home/"$SUDO_USER"/mindevenviro/configs/hosts  >| $tmpfolder/hosts 2>/dev/null ;
	cp -f $tmpfolder/hosts /etc/hosts 2>/dev/null ;
	chown root:root /etc/hosts ;
	chmod 644 /etc/hosts ;
fi
