#!/bin/bash
# mindevenviro serv-if-up
# serv-if-up (daemon) : restarts servers and notify

###     WARNING:    DON'T EDIT ANYTHING BELOW       ###

LANG="C";
readonly empty='';
readonly empty02='';

		if [[ "$EUID" != "0" ]] || [[ "$(ps ax | grep -v grep | grep -v nano | grep -v geany| grep redundanz | cut -f2 -d\ ) " = "$empty" ]] ;
	then
		echo "Hi $USER, this script restart servers and notify if error and or success" ;
		echo "USAGE: sudo redundanz -m" ;
		exit 0 ;
else
	if [[ "$(ps aux | grep -v grep | grep -v nano | grep -v geany | grep redundanz | awk '{print $2}' | wc -l) " -gt "1" ]] ;
then

# temp folder
		if [[ "$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" != '' ]] ; 
	then
		tmpfolder="$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" ;
	else
		tmpfolder="/tmp" ;
fi
# temp folder END
touch "$tmpfolder/root_mail_status"
# name vars
webserver="apache2" ;
datenbank="mysql" ;
mta="sendmail" ;
mailer="sendmail" ;
noHome="No Home Partition on this computer" ;
WARN01="80" ;
WARN02="85" ;
# name vars END

# message
senddingEmail(){
cat << EOM | sendmail root@localhost

$(cat "$tmpfolder/root_mail_status")

EOM
}

# checks if apache2 is up, if false restarts
apacheUP(){
	/etc/init.d/"$webserver" stop ;
	if /etc/init.d/"$webserver" start > "$tmpfolder/root_mail_status" ;
then

/etc/init.d/"$webserver" status >> "$tmpfolder/root_mail_status" ;

echo "$?" >> "$tmpfolder/root_mail_status" ;

senddingEmail &

	else

/etc/init.d/"$webserver" status > "$tmpfolder/root_mail_status" ;
date "+Start Attempt $webserver, Failure Time: %H.%M" >> "$tmpfolder/root_mail_status" ;

senddingEmail &

fi
}
# apacheUP END

# sendmailUP checks if sendmail is up, if false restarts
sendmailUP(){
checkprog2=$(whereis "$mta" | awk '{print $2}') ;
/etc/init.d/"$mta" stop ;
	if [[ -e $checkprog2 ]] && /etc/init.d/"$mta" start > "$tmpfolder/root_mail_status" ;
then
	/etc/init.d/"$mta" status >> "$tmpfolder/root_mail_status" ;

	echo "$?" >> "$tmpfolder/root_mail_status" ;

senddingEmail &
	else

	/etc/init.d/"$mta" status  > "$tmpfolder/root_mail_status" ;
	date "+Start Attempt $mta, Failure Time: %H.%M" >> "$tmpfolder/root_mail_status" ;

senddingEmail &
fi
}
# sendmailUP END

# mysqlUP checks if mysql is up, if false restarts
mysqlUP(){
/etc/init.d/"$datenbank" stop ;
	if /etc/init.d/"$datenbank" start > "$tmpfolder/root_mail_status" ;
then
	/etc/init.d/"$datenbank" status >> "$tmpfolder/root_mail_status" ;

	echo "$?" >> "$tmpfolder/root_mail_status" ;

senddingEmail &
	else

	/etc/init.d/"$datenbank" status > "$tmpfolder/root_mail_status" ;
	date "+Start Attempt $datenbank, Failure Time: %H.%M" >> "$tmpfolder/root_mail_status" ;

senddingEmail &
fi
}
# mysqlUP END

# checkfreeSpace check for drive space and notify if over limit
checkfreeSpace(){
IFHOMEEXIST=$(df -h | grep -E /home$) ;
SIZEONHOME=$(df -h | grep -E /home$ | awk '{print $2}') ;
SIZEON=$(df -h | grep -E /$ | awk '{ print $2 }') ;
USEDON=$(df -h | grep -E /$ | awk '{ print $3 }') ;
INODES=$(df -i | grep -E /$ | awk '{ print $2 }') ;
FREEINODES=$(df -i | grep -E /$ | awk '{ print $4 }') ;

	if [[ "$IFHOMEEXIST" = '' ]] ;
then
	PERCENTUSED01=$noHome ;
fi

cat << EOM | sendmail root@localhost

Subject:running_out_of_disk_space

_________________________________________________
/


redundanz: On host $(uname -n) :: ;

Warn percentage on /: $WARN01 %

Used percentage on the root@localhost /: $PERCENTUSED01

Inodes on host $(uname -n): $INODES

Size on /: $SIZEON GB

Used Inodes on /: $USEDON .

Free Inodes on host $(uname -n): $FREEINODES



_________________________________________________
/home


Warn percentage on /home: $WARN02 %

Used percentage on /home: $PERCENTUSED01

Size on /home: $SIZEONHOME GB

EOM
}
# END checking free space

# loop
		while true
	do
		if [[ "$(ps aux | grep -v grep | grep -v geany | grep -v nano | grep shi3lD | awk '{print $2}' | wc -l)" = "0" ]]
	then
		killall -15 dhclient ;
	fi
        if [[ "$(netstat -an | grep LISTEN | grep :80 | awk '{print $4}' | tail -n1)" = '' ]] ;
	then
		apacheUP && wait && sleep 1 ;
	fi
        if [[ "$(netstat -an | grep LISTEN | grep :25 | awk '{print $4}' | tail -n1)" = '' ]] ;
	then
		sendmailUP && wait && sleep 1 ;
	fi
        if [[ "$(netstat -an | grep LISTEN | grep :3306 | awk '{print $4}' | tail -n1)" = '' ]] ;
	then
		mysqlUP && wait && sleep 1 ;
	fi
		if [[ "$WARN01" -lt "$(df -h | grep -E /$ | awk '{ print $5 }' | sed -n 's/%//p')" ]] || [[ "$WARN02" -lt "$(df -h | grep -E /home$ | awk '{ print $5 }' | sed -n 's/%//p')" ]] ;
	then
		checkfreeSpace && wait && sleep 1 ;
	fi
	sleep 3 ;
done
# loop end
fi
fi
# END
