#!/bin/bash
# mindevenviro-fanciful stop_shield 
###     WARNING:    DON'T EDIT ANYTHING BELOW	###

LANG="C";
IFS=$(echo -e "\n\b");
nnumberOFinterface="0";
readonly empty='';

		if [[ "$EUID" != "0" ]] || [[ "$(ps ax | grep -v grep | grep -v nano | grep -v geany| grep redundanz | cut -f2 -d\ ) " = "$empty" ]] ;
	then
		echo "USAGE: sudo shi3lD, shut Iface and network related apps down." ;
		exit 0;
else

# temp folder
		if [[ "$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" != '' ]] ;
	then
		tmpfolder="$(df -h | grep -E shm$ | cut -f2 -d% | tr -d '\ ')" ;
	else
		tmpfolder="/tmp" ;
fi
# temp folder END

stop_Ppp(){
		echo -e " ... stopping connections\n" ;
		killall -15 dhclient 2>/dev/null && wait ;
		killall -15 wpa_supplicant 2>/dev/null && wait ;
		sudo ip link set dev "$(cat "$tmpfolder"/interface)" down && wait ;
		killall -15 firefox-esr 2>/dev/null && wait ;
		killall -15 pidgin 2>/dev/null && wait ;
		killall -15 vlc 2>/dev/null && wait ;
		killall -15 tor 2>/dev/null && wait ;
}

# ASK
  case "$1" in
        --stop)
      shift 1;
      stop_Ppp "$@" && exit 0 ;
      ;;
  esac
fi
